### ISSUE TITLE
onderzoeken of de productuitvoering definitief verwijderd kan worden

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#200]
We zullen samen met gemeenten en met de NP moeten onderzoeken of de productuitvoering definitief verwijderd kan worden of dat we deze in een latere sprint alsnog gaan ingebouwen. #20

**Comment by FrankLieuwen** [comment]
@markbacker wil jij dit oppakken met NP?

**Comment by markbacker** [comment]
Gisteren besproken met de werkgroep informatiemodel (14 dec 2021).

Er worden door de landelijke redactie zowel productvarianten als procedurevarianten onderkent.

Voorbeeld productvariant
- hondenbelasting voor grote hond of kleine hond

Voorbeeld procedurevariant
- aanvraag paspoort normaal of spoed.

Voor beide varianten is voorlopig besloten dat dit tekstueel wordt opgelost. De gemeente redacties moeten de verschillen in de tekstblokken duiden.

De tekstuele oplossing geldt, totdat uit het schrijven van de standaardteksten naar boven komt dat dit niet houdbaar is.

**Comment by markbacker** [comment]
De productuitvoering moet overigens nog wel uit het informatiemodel gehaald worden. Ik ga nog voorstellen dat te doen.

**Comment by FrankLieuwen** [comment]
ik lees dus dat de productuitvoering definitief verwijderd kan worden

**Comment by joeribekker** [comment]
Check, hij is er uit :)

**Comment by markbacker** [comment]
> ik lees dus dat de productuitvoering definitief verwijderd kan worden

Dat is wat snel geconcludeerd. Je leest over het laatste zinnetje heen:
> De tekstuele oplossing geldt, totdat uit het schrijven van de standaardteksten naar boven komt dat dit niet houdbaar is.

Maar zonder tegenbericht geldt inderdaad dat we kunnen uitgaan van productbeschrijvingen zonder expliciete productuitvoeringen
