### ISSUE TITLE
onderzoeken hoe in de UPL burger en/of ondernemerproducten worden vastgelegd

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#202]
In de UPL lijsten (zie #116) wordt nu met de kolommen burger en bedrijf vastgelegd of een product is bedoeld voor de burger, ondernemer of voor burgers én ondernemers

Indien een product bedoeld is voor burger én ondernemers dan wordt nergens vastgelegd of dit een producttekst is of voor beide doelgroepen of dat er aparte teksten zijn voor iedere doelgroep.

in de Excel spreadsheet kan dit wel expliciet worden vastgelegd 
- bijvoorbeeld de onroerendezaakbelasting (ozb) met een regel voor burgers én ondernemers
   - zie ook dat beide regels een ander SDG thema hebben
- maar ik vind geen regel met in één regel 'burger en ondernemers'
   - of kan dit niet en moeten er altijd aparte teksten zijn? Dat lijkt mij niet

Hoe matched de UPL nu op de spreadsheet?

**Comment by mrtn78** [comment]
> We gaan Logius verzoeken de lijst UPL-SDG-Informatiegebied uit te breiden met een kolom doelgroep.

@markbacker heb jij dit verzoek inmiddels al gedaan bij Marco Aarts?
inmiddels is wel de productenlijst versie 1.4 opgeleverd

**Comment by markbacker** [comment]
Het geheugen is weer opgefrist. Martin en ik hebben dit besproken met Logius.

In de SDG verordening is vastgelegd dat de thema-indeling expliciet gekoppeld is aan de doelgroep:
- themacodes a t/m i zijn voor burgerproducten
- themacodes j t/m q zijn voor ondernemerproducten

Met deze expliciete koppeling kan dus uit de UPL lijst eenduidig worden bepaald onder welke thema een burger- of ondernemerproduct valt.

**Let op**: het is mogelijk dat een één product valt onder meerdere SDG thema's. Voorbeeld: 
- kinderopvangtoeslag; een burgerproduct dat is ingedeeld onder de thema's E1 en G1.

Een gemis is dat er - voorzover ik weet - geen informatiemodel is van de UPL tabellen

**Comment by joeribekker** [comment]
Helder, de technische uitwerking was al gedaan in #275 

Ik sluit dit ticket daarom.
