### ISSUE TITLE
Als gemeentelijk redacteur wil ik via versiebeheer oude versies terughalen / inzien

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#205]
Ayse Bor  •  26 okt
Kun je via versiebeheer oude versies terughalen / inzien? Of is er een archief? Bijvoorbeeld als je tijdelijke aanpassingen hebt en na een bepaalde datum wil je de huidige tekst weer live zetten.

_Voted +1_

**Comment by joeribekker** [comment]
Inschatting:

* [ ] Verschillen zien: 4 dagen
* [ ] Oude versie terugzetten: 2 dagen

**Comment by FrankLieuwen** [comment]
Prio L gemarkeerd, onderin backlog voor eventueel volgende Fase

**Comment by mrtn78** [comment]
Deze gaan we niet meer oppakken
