### ISSUE TITLE
Als er een aangepaste specifieke tekst is ingevoerd door een gemeente kan hierin dan met highlight functie worden weergegeven waar deze afwijkt op de standaardtekst

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#206]
Holger Peters  •  26 ok

Wens: Als er een aangepaste specifieke tekst is ingevoerd door een gemeente kan hierin dan met highlight functie worden weergegeven waar deze afwijkt op de standaardtekst. Ter voorkomen van zoiets als "zoek de 7 verschillen"

_Voted +1_

**Tasks**

It's very similar to https://github.com/maykinmedia/sdg-invoervoorziening/issues/215 but, it compares the specific text, with the standard text.

* [x] Add diff to compare municipality text with standaard text (see below):

* The diff is implemented on the edit page, when using the preview (ie. the "Tekst aanpassen" link was not yet clicked).
* The diff compares the text in the edit page, with the active standard text

![image](https://user-images.githubusercontent.com/96970/145993686-34d88386-8b13-4bd8-93fd-d8e395b7f018.png)

**Comment by joeribekker** [comment]
As discussed, please add border around the non-editable text:

```
    border: 1px solid var(--ck-color-base-border);
    background-color: hsl(0deg 0% 90%); /* but instead use the sass var for darker gray that we already have */
```
