### ISSUE TITLE
Check: Is het mogelijk om meerdere locaties te koppelen aan een product. In de gemeente waar ik woon zijn bijvoorbeeld 2 stortlocaties voor grofvuil met verschillende openingstijden

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#207]
Holger Peters  •  26 okt

Check: Is het mogelijk om meerdere locaties te koppelen aan een product. In de gemeente waar ik woon zijn bijvoorbeeld 2 stortlocaties voor grofvuil met verschillende openingstijden. Ook het voorbeeld van grote gemeenten met meerdere stadskantoren in de wijken.

_Voted +1_

**Comment by joeribekker** [comment]
Ja, dit kan
