### ISSUE TITLE
Vraag: Is er in de test- / ontwikkelomgeving al een URL beschikbaar  met de API waar jullie de standaard teksten ophalen op basis van de UPL naam.

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#208]
Holger Peters  •  26 okt
Vraag: Is er in de test- / ontwikkelomgeving al een URL beschikbaar  met de API waar jullie de standaard teksten ophalen op basis van de UPL naam. Het is handig als we deze al hebben zodat we hier als gemeenten in onze PDC's al gebruik van kunnen maken.  Zo niet, is hier dan al een beschrijving van beschikbaar?

**Comment by joeribekker** [comment]
Zeker Holger, zie hier: https://sdg-invoervoorziening.maykin.nl/api/v1/producten?upnLabel=paspoort&catalogus=a52f5d02-af3f-4ffc-a6e3-5d772d4dfb16
