### ISSUE TITLE
Als redacteur heb ik de mogelijkheid om tabellen in te voegen

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#209]
Sandra Sjamaar  •  26 okt
Wens voor de editor: een mogelijkheid om tabellen in te voegen/

**Tasks**

* [x] Add table support in the CK-editor.

**Comment by joeribekker** [comment]
@FrankLieuwen doet uitspraak

**Comment by FrankLieuwen** [comment]
Voor nu buiten scope

**Comment by FrankLieuwen** [comment]
Navraag bij enkele ervaren redacteuren heeft geleerd dat het inderdaad zeer wenselijk is om tabellen te kunnen gebruiken om bijvoorbeeld prijzen en tarieven te kunnen tonen. Voioirwaarde is echter wel dat deze toegankelijk op de NP worden weergegeven.

**Comment by joeribekker** [comment]
Aan de genoemde voorwaarde kan alleen NP iets zeggen
