### ISSUE TITLE
Als redacteur beschik ik over een herkenbare call to action

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#210]
Sandra Sjamaar  •  26 okt
Wens voor de editor: een herkenbare call to action, liefst een knop.

**Comment by joeribekker** [comment]
@FrankLieuwen doet uitspraak

**Comment by FrankLieuwen** [comment]
we sturen een label mee zodat de CTA op NP kan worden ontsloten (geldt voor de verwijzingslinks)
voor het overige zal er bij de ontvangende partij e.e.a. moeten worden ingeregeld
