### ISSUE TITLE
Als redacteur wil ik producten kunnen invoeren in de acceptatieomgeving

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#221]

**Comment by joeribekker** [comment]
Testomgeving is gereed gebruik. Acceptatie wordt nog aan gewerkt.

Ticket is geblokkeerd door:

* [ ] Inrichting acceptatieomgeving (#155)
* [ ] Regelen van domeinnamen (#256)
* [ ] Regelen van certificaten (#38)
