### ISSUE TITLE
Voor het beheer van account is een SMTP voorziening voorhanden

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#227]
of minstens een manier om mail vanaf de server te verzenden

**Tasks**

* [ ] Configure email service for acceptance and production

**Comment by mrtn78** [comment]
de aanvraag is gedaan me tde vraag of we uit naam van 
singledigitalgateway@vng.nl mails kunnen versturen.

**Comment by mrtn78** [comment]
op 21-12-2021 opnieuw navraag gedaan bij VNG Servicemanagement

**Comment by mrtn78** [comment]
emails worden verstuurd uit naam van no-reply@vng.nl. 
Dit adres wordt eigenlijk alleen gebruikt voor uitgaande mail die de invoervoorziening genereerd bij het aanmaken van accounts en het resetten van wachtwoorden. het bovengenoemde functionele adres is niet in gebruik en kan nog indien gewenst worden aangevraagd als standaard team mailbox via de reguliere Kantoorautomatisering.
