### ISSUE TITLE
Als gemeente wil ik kosten gestructureerd kunnen toevoegen aan producten...

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#235]
...zodat deze gebruikt kunnen worden door applicaties (betalen voor producten via formulieren) en ik deze niet apart hoef bij te houden.

Het tekstveld `kostenEnBetaalmethoden` is niet gestructureerd genoeg om hier netjes mee om te gaan.

**Comment by markbacker** [comment]
Het tekstveld `kostenEnBetaalmethoden` blijft ongewijzigd. Dit is de tekst die gepubliceerd wordt op het NP

Naast deze tekst kan de gemeente ook een veld `kostenVanaf` invullen. Hier wordt gestructureerd de laagste prijs ingezet.
Overweging: ook een veld `kostenMaximaal` toevoegen?

Wat betekent dit voor een gemeente redactie:
- redactie is verantwoordelijk voor het kloppend houden van de laagste bedrag op twee plekken
- we leveren het veld 'kostenVanaf' mee in de API, maar de redactie kan deze niet terugvinden op het portaal
- redactie weet niet in welke context het laagste bedrag ooit gebruikt gaat worden.
- redactie kan geen verantwoordelijkheid nemen voor misinterpretaties van het veld `kostenVanaf`

Willen we dit?

**Comment by FrankLieuwen** [comment]
voor nu buiten scope
