### ISSUE TITLE
Feedback op de producten endpoint:

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#251]
Namens DOP

Feedback op de producten endpoint:

Requirement: wij willen producten kunnen opvragen adhv. een OWMS resource identifier van een organisatie ipv. een uuid die door de API is genereerd. Bijv. alle producten ophalen die gekoppeld zijn aan gemeente Rotterdam: /api/v1/producten?organisatie=https://standaarden.overheid.nl/owms/terms/Rotterdam Overgenomen in ticker #258

- [x] #259

- [x] Requirement: Je kan producten filteren op publicatieDatum (laatstgewijzigd datum), maar publicatieDatum wordt niet getoond in het JSON document (response) van een product. Dit willen we wel.

- [x] #260

- [x] #261

- [x] #262

Feedback algemeen

- [x] #263

- [x] #264

**Comment by joeribekker** [comment]
@FrankLieuwen splits jij deze op? Een van de punten was al opgelost, dus die kan in dit ticket blijven.

**Comment by FrankLieuwen** [comment]
@joeribekker jasegels, lang leve de 'convert to issue' functie
