### ISSUE TITLE
Domeinnamen aanleveren

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#256]
Voor acceptatie en productie hebben we domeinen nodig om te koppelen aan de applicatie.

**Comment by mrtn78** [comment]
ik heb reactie van een VNG collega dat hij de DNS records voor ons kan aanmaken en heb Maykin gevraagd deze aan te leveren voor de ACC omgeving. Ik stel voor dit verder via de mail af te handelen en de DNS gegevens niet publiekelijk in deze repo op te nemen.

**Comment by mrtn78** [comment]
Een overzicht van de domeinen en de aangevraagde DNS records is uitgewerkt in [de WIKI van deze repo](https://github.com/maykinmedia/sdg-invoervoorziening/wiki/DNS-settings)
