### ISSUE TITLE
Dop wil producten kunnen opvragen adhv. een OWMS

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#258]
- [ ]  Requirement: wij willen producten kunnen opvragen adhv. een OWMS resource identifier van een organisatie ipv. een uuid die door de API is genereerd. Bijv. alle producten ophalen die gekoppeld zijn aan gemeente Rotterdam: /api/v1/producten?organisatie=https://standaarden.overheid.nl/owms/terms/Rotterdam

overgenomen uit #251

**Comment by joeribekker** [comment]
Dit kan een additioneel filter zijn, geen probleem. Ik tag @HenriKorver om iets te zeggen of we UUIDs moeten gebruiken of altijd die OWMS id.

**Comment by joeribekker** [comment]
In overleg met Henri besloten op:
```
?organisatie_uuid=<uuid>
?organisatie_owms=<owms id>
```

**Comment by joeribekker** [comment]
Wordt getackled in #274
