### ISSUE TITLE
Opmerking/Vraag: producten zijn te filteren op publicatieDatum. Is publicatieDatum gelijk aan laatstgewijzigd datum? Want filteren op laatstgewijzigd datum is wat wij willen.

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#259]

**Comment by joeribekker** [comment]
Discussie hierover staat in #30 waar @markbacker kijkt of we publicatiedatum gebruiken ipv laatst gewijzigd.

**Comment by markbacker** [comment]
De API stelt de meest actuele gepubliceerde teksten beschikbaar. Filteren op de publicatieDatum levert dus de set met meest actuele gepubliceerde teksten.

**Comment by FrankLieuwen** [comment]
Per mail beantwoord
