### ISSUE TITLE
[US-33] Als gedeelde redactie wil ik voor ieder soort producten instructies (eisen en tips voor dat soort specifieke tekst) kunnen beheren

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#26]
..., opdat de specifieke teksten voldoen aan de SDG kwaliteitseisen

Zie paragraaf 5.5.4 Indeling van productbeschrijvingen

**Verduidelijking nodig**

Hoe zien we dit voor ons? De teksten achter de i-tjes? Is dit nog relevant?

**Comment by FrankLieuwen** [comment]
i-teksten worden niet beheerbaar maar voor nu éénmalig ingevoerd
