### ISSUE TITLE
Requirement: Locaties data direct meegeven in het JSON document ipv. alleen de uuid van locaties. Locaties zoals ze nu zijn meegegeven (als url naar de locatie endpoint) is voor ons niet werkbaar.

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#260]

**Comment by joeribekker** [comment]
"Niet werkbaar" lijkt me overdreven als een API-call ~0,01s duurt maar ik mis de context/scenario's.

Er zijn grofweg 2 scenario's denkbaar:

**1. Lijst van alle producten met hun locaties tonen**

Bijvoorbeeld voor een specifieke organisatie.

Dit kan met 2 API-calls:
1. `GET /producten?organisatie=abc123`  Dit geeft alle producten en hun locatie resource, binnen deze organisatie
2. `GET /locaties?organisatie=abc123`  Dit geeft all locaties voor deze organisatie

Je kan nu zonder dat er gedupliceerde data (dezelfde locatie details bij elk product) over de lijn gaat, de resultaten combineren en presenteren (supersnel, heel eenvoudig).

**2. Een enkel product ophalen en de locatie tonen**

Dit kan met 2 API-calls:
1. `GET /producten/def678`  Dit geeft de details van het product en de locatie link. Stel er komen 1 locatie terug (het overgrote deel van de gemeente heeft 1 locatie voor zover ik weet).
2. `GET /locaties/567bcd`  Dit geeft de locatie details

De 2e call is inderdaad nodig om locatie details op te halen voor dat product omdat die niet bij het product zit. De overhead hiervan is echter vele malen kleiner dan als je in scenario 1 uitvoert waarbij steeds dezelfde locatie details voor alle producten over de lijn gaan.

Als scenario 2 door alle Nationale Portalen de meest gebruikte is, dan kunnen we locatie alsnog inline ontsluiten. Alternatief is de `?expand` parameter.

**Comment by joeribekker** [comment]
Bespreken met Henri:

API Strategie zegt hier niet zo veel over. Wat we kunnen doen is de list view laten we met linkjes, en met detail view doen we inline expanded.

**Comment by FrankLieuwen** [comment]
@markbacker wil jij dit ophalen bij NP?

Verduidelijk met NP

Welke calls gaan ze precies doen?

**Comment by joeribekker** [comment]
@dariomory Please ALSO serialize location inline for products
