### ISSUE TITLE
Vraag: Wat zijn de velden productAanwezig en productAanwezigToelichting in de producten endpoint response?

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#261]

**Comment by markbacker** [comment]
Dit staat in het informatiemodel. 


| Attribuut  (API) | Label burger en ondernemer | Label redactie | Omschrijving |
| ---------------- | -------------------------- | -------------- | ------------ |
| ProductAanwezig            | -           | Voert u dit product? | De decentrale overheid geeft  expliciet aan of een product wel of niet gevoerd wordt.          Met dit attribuut wordt voor de nationale portalen expliciet gemaakt  of:     (1) een gemeente een product nog niet heeft ingevoerd óf      (2) het product überhaupt niet voert.           De decentrale overheden zijn zelf verantwoordelijk voor het bepalen welke  SDG producten gevoerd worden. Er is geen lijst waarop is vastgelegd welke  producten wettelijk verplicht zijn. <br>Bijbehorende bedrijfsregel:<br>- Indien ja, dan moet de specifieke informatie van het product gevuld  zijn<br>- Indien nee, dan moet het attribuut ProductAanwezigToelichting gevuld zijn |
| ProductAanwezigToelichting | Toelichting | Toelichting          | Toelichting die op het portaal  getoond gaat worden, indien ProductAanwezig=nee.           - Standaardtekst: <decentrale overheid> voert product <producttitel>  niet     - of: te overschrijven met vrije tekst van decentrale overheid |

**Comment by joeribekker** [comment]
@markbacker ik vermoed dat DOP gewoon de nieuwe versie van het IM nog niet had.

**Comment by markbacker** [comment]
Frank, geef jij het antwoord door?

**Comment by FrankLieuwen** [comment]
is per mail beantwoord
