### ISSUE TITLE
Verwijzingen naar een organisatie (ook) doormiddel van een OWMS resource identifier. Dus niet (alleen) dmv. een door de API gegenereerde UUID.

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#263]

**Comment by joeribekker** [comment]
Ik vraag het aan de API strategie expert :)

**Comment by joeribekker** [comment]
Besproken met Henri:

We expanden organisatie ook direct, dan zit owmsIdentifier er direct bij in de organisatie.

**Bespreken met NP**

Is dit alleen nodig op detail of ook lijst niveau?

**Comment by joeribekker** [comment]
Wordt getackled in #274
