### ISSUE TITLE
Verwijzingen naar een product (bijv. gerelateerdeProducten) ook d.m.v. een upnUri.

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#264]

**Comment by joeribekker** [comment]
Dit kan helaas niet omdat gemeenten soms meerdere producten aan 1 UPN kunnen hangen. Het systeem staat dat nu niet toe vanuit gebruikers maar op beheer niveau wel.

De UPN URI is daarmee niet uniek (genoeg) voor deze producten in deze catalogus.

**Comment by markbacker** [comment]
Dit moet wel kunnen. Uitgangspunt is dat gemeenten voor één UPN en één doelgroep één specifieke tekst in twee talen schrijven. Deze sleutels (plus de gemeente OWMS identifier) wijzen uniek naar een specifieke tekst.

Ik neem even aan dat met dit issue hetzelfde bedoeld wordt als het kenmerk 'Product valt onder' dat in het Informatiemodel 1.4 in de steigers staat.

Uit het nog te akkorderen IM1.4:
`ValtOnderProduct` - Waar het merendeel van de gemeenten  een product (product A) wél voert, en een enkele gemeente afwijkt door deze onder te brengen bij ‘(product B)’, moet deze gemeente eenvoudig vanuit de invoervoorziening kunnen doorverwijzen ván product A naar product B.
  - redacteur kan met een pull-down met productnamen een `ValtOnderProduct` selecteren
  - in de invoervoorziening is dit geen link naar het valt onder product

De portalen tonen product A met de melding dat het product valt onder product B. Product B wordt getoond als link

Voorbeeld de terrasvergunning. 
_Bij veel gemeenten valt de terrasvergunning onder de horecavergunning. In plaats van dat de gemeente aangeeft dat de terrasvergunning niet aanwezig is, wordt meegegeven dat de terrasvergunning valt onder de horecavergunning._

**Comment by joeribekker** [comment]
De relatie UPN - Generiek product - Specifiek product wordt dan allemaal een 1-op-1 relatie. Volgens mij is dat anders besproken, los van wat er in het huidige of toekomstige IM staat. Maar goed, als dat het idee is dan kan het in ieder geval technisch wel.

Dan heb ik @HenriKorver nog getagged over de wenselijkheid van het gebruik van een andere identifier dan een UUID.

**Comment by joeribekker** [comment]
In overleg met Henri kunnen we een object ipv een link toevoegen aan gerelateerde producten, bijvoorbeeld:

```
"gerelateerdeProducten": [{
  "url": "http://www...",
  "upnUri": "http://www...",
  "upnLabel

...
```

**Comment by joeribekker** [comment]
Wordt getackled in #274

**Comment by joeribekker** [comment]
@markbacker We voegen dus `upnUri` toe aan de relatie informatie. Echter, op basis van het uiteindelijke `upnUri` kan je dus niet meer terug redeneren naar een product, zonder kennis van de doelgroep.

Ik maak verder een nieuw ticket om producten te splitsen op basis van doelgroep.
