### ISSUE TITLE
Als SDG projectmanager wil ik producten kunnen prioriteren

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#266]
opdat ik met gemeenten en portalen afspraken kan maken over batches van te implementeren producten

De SDG productenlijst is nu opgedeeld in een shortlist en een longlist. De implementatie start met de shortlist, met daarbij de afspraak dat:
- de NP de generieke teksten gereed hebben
- de GGR de standaardteksten gereed hebben
- de gemeente redacties kunnen starten met de specifieke teksten van producten waarvoor een standaardtekst beschikbaar is

Openstaande vragen:
- de short/longlist is nu vastgelegd in de productenlijst. Gaan we dit projectgegeven expliciet vastleggen in de invoervoorziening?
- wat is de betekenis achter short- en longlist?
- zijn twee prioriteiten voldoende om te sturen tijdens de implementatie?

**Comment by mrtn78** [comment]
Update openstaande vragen:

> de short/longlist is nu vastgelegd in de productenlijst. Gaan we dit projectgegeven expliciet vastleggen in de invoervoorziening?
**Nee, de productenlijst is vastgelegd in de UPL**
> wat is de betekenis achter short- en longlist?
**Dit was alleen relevant voor het uitzoekwerk en de afstemming tussen VNG en NPs. de betekenis en typering is niet meer vastgelegd in de UPL en SDG**
> zijn twee prioriteiten voldoende om te sturen tijdens de implementatie?
**Ik stel voor om als team te beslissen of prioritering wenselijk is en met welke prioriteiten (H-M-L / 1-2-3-4-5 / of iets anders)**

**Comment by joeribekker** [comment]
Volgens mij niet meer relevant?

**Comment by mrtn78** [comment]
Niet meer relevant. deze gaan we niet meer oppakken
