### ISSUE TITLE
Als redacteur wil ik de mogelijkheid hebben om teksten te kunnen previewen op een frontend van de invoervoorziening.

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#291]
De concept teksten worden dan in een preview getoond die hoort bij het CMS.
Hiervoor wordt de templating nagebouwd van het ondernemersplein zodat dezelfde look & feel wordt ervaren.

**Comment by joeribekker** [comment]
Is het template al bekend?

**Comment by mrtn78** [comment]
Ik zou de frontend dynamisch maken zodat je kan verwijzen naar een dataset van de API en een CSS van een NP. door die 2 te combineren kan je dan de tekst in de specifieke opmaak laten zien.

**Comment by FrankLieuwen** [comment]
wordt opgepakt in issue #22
