### ISSUE TITLE
Make the labeled URLs pretty in read only mode.

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#297]
![image](https://user-images.githubusercontent.com/96970/146924464-f261cce5-ae20-4acc-a6af-e57fb50b977e.png)

**Tasks**

* [x] Make the styling of links and labels nicer. Simply key: value is enough. Example: 

* Submit request: https://www.example.com
* Report missing: https://www.example.com

**Comment by dariomory** [comment]
Fixed in #301
