### ISSUE TITLE
[US-43] Als Nationaal portaal (KvK) wil ik van alle producten van alle gemeenten in bulk de wijzigingen vanaf een bepaalde datum kunnen ophalen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#30]
..., zodat ik mijn website periodiek kan synchroniseren

Het maken van een kopie van de gegevens staat op gespannen voet met het ?common ground? principe van ?data bij de bron?.

**Acceptatiecriteria** :
* De bestaande API functies worden uitgebreid met een functie om alleen wijzigingen binnen een bepaald timeframe op te halen.

**Tasks**

* [x] Add the ability to add `__gte` to the `publicatiedatum` filter.

**Comment by joeribekker** [comment]
@markbacker Wat is het verschil tussen "wijzigingsdatum" en "publicatiedatum"? Ik neem aan dat alleen product teksten die gepubliceerd zijn revevant zijn? VOor gepubliceerde product teksten geldt dat de wijzigingsdatum gelijk is aan de publicatiedatum.

We hebben nu: `/api/v1/producten?publicatiedatum__gte=01-01-2021` maar wellicht moet er nog wat zijn...?

**Comment by markbacker** [comment]
Daar heb je een goed punt met het verschil tussen wijzigingsdatum en publicatiedatum. Het informatiemodel kent geen publicatiedatum.

Komt er op neer dat wat jij nu wijzigingsdatum noemt, alleen betekenis heeft binnen de invoervoorziening voor de gemeente redacties. 
- wijzigingsdatum -> wie heeft wanneer een nieuwe versie van een specifieke tekst aangemaakt in de invoervoorziening .
- publicatiedatum -> datum waarop de wijziging voor de buitenwereld zichtbaar wordt. Dit is de betekenis van het veld `DatumWijziging` in het informatiemodel. De `DatumWijziging` wordt op het NP getoond. 

Ik zie nu dat de API het veld `publicatiedatum` kent. 

Het wordt een stuk duidelijker als in het informatiemodel het attribuut `DatumWijziging` hernoemd wordt naar `Publicatiedatum`. Die wijziging ga ik voorstellen/doorvoeren.

**Comment by markbacker** [comment]
> We hebben nu: /api/v1/producten?publicatiedatum__gte=01-01-2021 maar wellicht moet er nog wat zijn...?

Voor nu is dat voldoende. De kvk kijkt nu mee naar de API. Volgens mij zijn zij aan het overwegen om toch geen kopie bij te houden.

**Comment by joeribekker** [comment]
Ik had em er toch even bijgepakt:

![image](https://user-images.githubusercontent.com/96970/143457361-ffa0821e-f3bb-4679-a366-4f88734b55b5.png)

Je hebt gelijk, publicatiedatum is (groen) alleen voor de invoervoorziening zelf. Eigenlijk is wijzigingsdatum iets interns nu, omdat bij concepten deze datum wel wijzigt, maar de publicatiedatum niet.

**Comment by markbacker** [comment]
In het informatiemodel is het veld DatumGewijzigd nu hernoemd naar publicatiedatum.
