### ISSUE TITLE
Unknown users shown under Gebruikers

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#340]
Not 100% sure why but the bottom two users are not linked to this municipality but are shown under "Gebruikers" and cannot be deleted.

![image](https://user-images.githubusercontent.com/96970/148202122-518645f5-c27b-434f-adbd-88b98b4b0f0e.png)

I did notice that they both don't have ANY "LokaleOverheid" linked to them in the admin.

Only users that have a role in a "LokaleOverheid" should show up.

**Comment by dariomory** [comment]
This is a fix for issue #273 (point 2)

Could be implemented differently or removed as suggested here.
