### ISSUE TITLE
Vraag: Generiek product huisvestingsvergunning niet zichtbaar

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#356]
Ik heb het generiek product  huisvestingsvergunning via /admin van teksten voorzien. De teksten worden niet getoond boven een standaardtekst of specifieke tekst.

Dit werkt wel voor de standplaatsvergunning. Wat opvalt is dat in het dashboard bij standplaatsvergunning een EU burger te zien is, bij huisvestingsvergunning niet.

Hoe zorg ik ervoor dat de generieke tekst getoond wordt?

**Comment by joeribekker** [comment]
> Ik heb het generiek product huisvestingsvergunning via /admin van teksten voorzien. De teksten worden niet getoond boven een standaardtekst of specifieke tekst.

Ik zie dat er 2 generieke producten zijn: 1 met doelgroep, en 1 zonder doelgroep. Komt omdat we de doelgroep-logica hebben aangepast. Heb em even omgehangen. Nu staat je tekst er wel: https://sdg-invoervoorziening.maykin.nl/organizations/1/catalogs/28/products/102/edit/
