### ISSUE TITLE
bugje: Filtering catalogus werkt niet in collapsed view

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#357]
In de [cataloguslijst ](https://sdg-invoervoorziening.maykin.nl/organizations/1/catalogs/) werken de [Niet gepubliceerd], [controle nodig], etc filters niet als de lijst collapsed is.

Zoeken in tekst en de EU burger en ondernemer filters werken wel collapsed.

**Comment by joeribekker** [comment]
Volgens mij wordt dit in #318 opgelost.

**Comment by markbacker** [comment]
#318 lijkt mij een ander issue. Dit issue geldt juist niet voor de filters EU burger en bedrijf. 

Eens met #318 dat het icoon ![image](https://user-images.githubusercontent.com/41415562/149081232-de2b1313-da81-498b-8223-d97298c79b38.png) moet laten zien wat de state is. 

Je moet kunnen zien of de lijst collapsed is of dat het filter een lege lijst opleverd.

**Comment by joeribekker** [comment]
Ik sluit het ticket ook niet :-) ik vermoed alleen dat #318  het oplost maar zo niet dan pakken we deze gewoon ook op.
