### ISSUE TITLE
[US-60] Als VNG functioneel beheerder wil ik de productcatalogi van gemeenten in een herindeling kunnen samenvoegen, 

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#36]
Als VNG functioneel beheerder wil ik de productcatalogi van gemeenten in een herindeling kunnen samenvoegen, opdat deze gemeenten met minimale inspanning en kans op fouten een nieuwe gezamenlijke catalogus kunnen maken?

**Verduidelijking nodig**

Technisch kan dit. Je kan een product "omhangen" van de ene gemeente naar de andere. Dit zorgt dan wel voor dubbele producten? Wie beslist welke blijft? Ik zie meer problemen dan oplossingen :)

**Tasks**

* [x] Add documentation for VNGR management

**Comment by mrtn78** [comment]
omhangen van de ene organisatie naar de andere lijkt me ook niet altijd de beste oplossing.

In de praktijk zijn er vaak 2 situaties bij dergelijke herindelingen:
1. gemeente A en B gaan samen. dit resulteert er in dat A wordt opgeheven en B alles van A overneemt. Soms wordt B ook nog hernoemd naar B2
2. Gemeente A en B gaan samen. daartoe wordt gemeente C gecreeerd. A en B worden opgeheven en alles wordt overgenomen door C. 

Het lijkt mij de beste oplossing dat:
1. VNGR de toegang tot de catalogi van meerdere gemeenten koppelen aan de accounts van de nieuwe of de blijvende organisatie. (handmatige beheeractie)
2. VNGR de naamswijzigingen doorvoeren (handmatige beheeractie)
3. De gemeentelijke redacteuren zelf de content over nemen en bewust opnieuw publiceren
4. De gemeentelijke redacteuren zelf aangeven dat de geen content meer deelt (via de API)
5. VNGR de organisatie en content na x jaar inactiviteit verwijdert (handmatige beheeractie)

**Comment by joeribekker** [comment]
Documentatie staat gereed in: https://github.com/maykinmedia/sdg-invoervoorziening/blob/master/docs/functioneel_beheer.md
