### ISSUE TITLE
Bug: Geen preview van productbeschrijving in gemeentelijke catalogus

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#364]
Zie https://sdg-invoervoorziening.maykin.nl/organizations/2/catalogs/2/products/215

De getoonde NL productbeschrijving is onterecht leeg.
- er is een generieke tekst
- er is een specifieke tekst

Het gekke is dat er wel een preview is in de referentiecatalogus van VNG
Zie https://sdg-invoervoorziening.maykin.nl/organizations/1/catalogs/28/products/61/

En om het af te maken. Het gaat ook mis in de referentiecatalogus bij een ander product. 
Zie https://sdg-invoervoorziening.maykin.nl/organizations/1/catalogs/28/products/124/

**Comment by joeribekker** [comment]
Ik haal deze uit de sprint, aangezien preview eerst goed gespecificeerd moet worden.

**Comment by markbacker** [comment]
Ik noem de pagina's hier per abuis preview, maar ik bedoel de openingspagina van een productbeschrijving (of hoe noem jij die pagina?)

De data is nu weg en de links werken dus niet meer. Maar ik vermoed dat dit nog steeds fout gaat (of de refresh van de data doet wonderen)

**Comment by joeribekker** [comment]
Ah, de detail pagina.

**Comment by joeribekker** [comment]
Verduidelijking: Dit komt doordat de gepubliceerde tekst `>` hanteert ipv `>=` waardoor vandaag publiceren pas morgen wordt getoond.
