### ISSUE TITLE
Beschrijven technische keuzen SDG product API

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#367]
Leg in de wiki vast welke technische - en beveiligingskeuzen gemaakt zijn bij de realisatie van de SDG product API. 

Deze beschrijving geldt als aanvulling op de OAS en dient zo concreet te zijn dat deze bouwbaar zijn voor de portalen en andere decentrale overheden.

Startpunt zijn de non-functionals, zoals beschreven in de specificatie van de invoervoorziening

Beschrijf:
- Welke standaarden zijn gevolgd
- Welke keuzen binnen de standaard zijn gemaakt
- Welke aanvullende keuzen zijn gemaakt

**Comment by joeribekker** [comment]
Voordat ik hier iets voor ga opstellen, wat zie je voor je? Is er een voorbeeld van een andere API?

**Comment by mrtn78** [comment]
Deze gaan we niet meer actief oppakken
