### ISSUE TITLE
Preview changes

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#371]
Blocked pending more desired changes to preview

**Tasks**

* [ ] Add generic product texts to preview feature

**Comment by markbacker** [comment]
Ter info

Het design van de preview moet inhoudelijk gelijk zijn aan het design van de portalen. Een productbeschrijving moet in de preview hetzelfde lezen als in een portaal.

Om dit te bereiken gaan de portalen (ondernemersplein én rijksoverheid.nl) een aantal design-uitgangspunten vastleggen op basis waarvan de portalen en de preview gerealiseerd gaan worden. De uitgangspunten worden vastgelegd in het informatiemodel.

De design uitgangspunten leggen onder andere vast: 
- volgorde tekstblokken, 
- globale positie verwijzing links
- globale positie organisatie, contactgegevens en locaties

**Comment by joeribekker** [comment]
Het is echt veel fijner als ze gewoon op basis van een API endpoint een preview kunnen tonen. Dan hoeft er geen design gekopieerd te worden of iets dergelijks. Wij ondersteunen dit nu al vanuit de SDG API.

Je houdt zo het design bij de bron en hoeft geen kopie in sync houden. Daarbovenop hebben de portalen toch al de code om op basis van de SDG API een pagina te tonen met als enige verschil dat de een een concept is en de ander een gepubliceerde product tekst.

**Comment by markbacker** [comment]
Eens dat dit beter zou zijn. Voor nu zijn er twee redenen waarom we dit nu toch bij de invoervoorziening moeten oplossen:
- de planningen lopen niet parallel; wij willen gemeenten zo snel mogelijk laten starten met het invoeren van hun producten, de portalen zijn dan nog niet zover.
- gemeenten moeten een concepttekst kunnen previewen voordat deze gepubliceerd wordt. Voor nu is het standpunt van DOP dat zij geen functionaliteit realiseren voor het tonen van concepten. 

Risico dat de preview de teksten toch anders toont is hoog, zeker omdat we de preview bouwen voordat het portaal gebouwd is.

**Comment by markbacker** [comment]
Overlapt met #418. 

Kan volgens mij gesloten worden.
