### ISSUE TITLE
Investigate "toeristenbelasting" missing from the CMS

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#373]

**Comment by joeribekker** [comment]
@mrtn78 @markbacker wat te doen hiermee?

**Comment by markbacker** [comment]
We moeten dit laten herstellen door Logius. Maar als dit moet wachten op de volgende release (eens per kwartaal), dan duurt het te lang en kan de GGR voor de toeristenbelasting geen standaardtekst schrijven.
@mrtn78 graag met Logius afstemmen

@joeribekker is het mogelijk om van de ingelezen UPL voor 1 of enkele producten de waarden tijdelijk (paar maanden) te overrulen? Of om tijdelijk de toeristenbelasting zelf te definieren. 
Dit is niet gewenst, maar ik kan me voorstellen dat iets vergelijkbaars nog wel een keer gaat gebeuren ..

**Comment by joeribekker** [comment]
Hmmm. Als we het zomaar aanpassen corrigeert de automatische sync het de volgende dag weer terug naar de incorrecte waarde.

We kunnen de automatische sync stop zetten en alleen op verzoek laten draaien. Maar we kunnen ook iets van "geforceerde waardes" toevoegen die altijd de automatische waarde overruled. Ik weet niet direct wat logischer is...

**Comment by markbacker** [comment]
Logius geeft door dat het opgelost is in de UPL. 

Als de gecorrigeerde UPL nu live staat, dan zouden we met één keer synchroniseren de toeristenbelasting weer moeten zien. Ik ben benieuwd

Bericht van Logius:
> KOOP heeft de codes van deze twee producten inderdaad per abuis leeg gemaakt bij de vorige update. Het betrof ook alleen deze twee producten. Ze zijn inmiddels weer toegevoegd.

**Comment by joeribekker** [comment]
Hij staat er nu 2x in. 1x voor bedrijf en 1x voor burger.

**Comment by FrankLieuwen** [comment]
in acc komt product 3 x voor, in prod staat het goed

**Comment by mrtn78** [comment]
Frank neemt dit door met Joeri. Op dit moment staat deze goed in de UPL maar staat het product  in acc 3x in de invoervoorziening ipv 2x. in Prod staart het wel goed.

**Comment by joeribekker** [comment]
Gaat vanzelf mee als we prod db naar acc gooien.
