### ISSUE TITLE
Als redacteur wil ik duidelijke labels bij de invoervelden

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#378]
- [ ] - Algemeen
(korte omschrijving van de procedure, waar vaak al verschillende opties worden
getoond)

- [ ] - Voorwaarden

- [ ] - Tarieven
(welke tarieven de gemeente hanteert om de hoogte van een aanslag te bepalen)

- [ ] - Nodig voor de aanvraag
(meenemen naar de afspraak of uploaden bij online aanvraag)

- [ ] - Aanvragen

- [ ] - Online

- [ ] - Aan de balie op afspraak of op inloop

- [ ] - Per post of schriftelijk

- [ ] - Kosten

- [ ] - Betalen
(beschrijving van hoe je kunt betalen)

- [ ] - Hoelang duurt het?

- [ ] - Bezwaar maken

- [ ] - Kwijtschelding

- [ ] - Ook nodig
(randvoorwaardelijk product)

- [ ] - Misschien ook nodig
(gerelateerde producten)

- [ ] - Vergoeding kosten
(vaak bij WMO producten)

**Comment by joeribekker** [comment]
Veel te onduidelijk wat wat moet zijn. Graag oud label -> nieuw label, als er nieuwe velden moeten komen ook aangeven.

**Comment by FrankLieuwen** [comment]
@markbacker wil jij je hier over buigen gezien de relatie met het informatiemodel?

**Comment by FrankLieuwen** [comment]
Labels zijn nu aanpasbaar, issue is gereed gemeld in overleg met Mark Backer
