### ISSUE TITLE
[NF-03] Beveiliging Create, Update & Delete

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#39]
Indien de producten API ook het schrijven van waarden gaat toestaan worden deze operaties conform de landelijke API strategie en de nog in ontwikkeling zijnde Digikoppeling profielen beveiligd met oAuth dan wel mTLS voor de beveiliging

**Comment by joeribekker** [comment]
We gaan dit voor nu niet doen, dus niet van toepassing. Aan @FrankLieuwen voor de definitieve call.

**Comment by FrankLieuwen** [comment]
Voiior nu inderdaad niet van toepassing, onderin backlog laten staan tot api definitief is
