### ISSUE TITLE
Remove "datumWijziging" from API and rename "publicatieDatum" to "laatstGewijzigd"

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#407]
Besproken met Elie, Hoang (DOP), Joeri, Mark:

**Tasks**

* [ ] Remove "datumWijziging" from API
* [ ] Rename "publicatieDatum" to "laatstGewijzigd"

**Comment by mrtn78** [comment]
Dit is 1 van  de wijzigingen conform het informatie model versie 1.6 zoals beschreven in #440

**Comment by joeribekker** [comment]
Nee @mrtn78 

Ik ben het niet eens met de wijziging. Via mail aangegeven bij @markbacker

**Comment by mrtn78** [comment]
Dit hangt samen met de wijzigingen in het informatiemodel v1.6 zoals beschreven in issue #440. Dit pakken we niet als los issue in deze vorm op.
