### ISSUE TITLE
Invoervoorziening bevat ook niet meer bestaande gemeenten

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#408]
Bij het inlezen van de gemeenten uit de owms tabel moet gefilterd worden op einddatum. 

Zie bijvoorbeeld de gemeente Zijpe. De gemeente Zijpe is 2012 onderdeel geworden van de gemeente Schagen

**Tasks**

* [x] Doubelcheck that organizations that have an expired enddate, their products are not accessible via the API

**Comment by joeribekker** [comment]
Wat wil je precies bereiken? Ik snap wel dat ze niet meer bestaan of gefuseerd zijn maar wat wil je functioneel wel/niet kunnen?

**Comment by markbacker** [comment]
Onder andere dat er geen catalogi worden aangemaakt voor niet bestaande gemeenten. 

En dat bijvoorbeeld https://sdg-invoervoorziening.maykin.nl/api/v1/organisaties alleen bestaande gemeenten retourneert ..

**Comment by joeribekker** [comment]
Dat laatste vind ik al genuanceerder liggen. Moet je straks geen catalogi meer kunnen opvragen van opgeheven gemeenten?

Denk dat we goed in kaart moeten brengen wat wel en wat niet.

**Comment by markbacker** [comment]
Daar heb je een goed punt. Hoe dit gaat werken met historie moeten we inderdaad nog bedenken. Bijvoorbeeld wat dit betekent voor het samenvoegen van catalogi van gemeenten na een herindeling. Voor nu buiten scope.

Binnen scope is dat de API alleen van bestaande gemeenten organisaties en catalogi publiceert.

**Comment by mrtn78** [comment]
Voor zover bekend bij mij en @markbacker is deze al opgelost. kan jij dat nagaan @joeribekker ?

**Comment by joeribekker** [comment]
Mja "opgelost".

De catalogi van een beindigde gemeente wordt simpelweg niet meer geupdate aan de kant van de SDG invoervoorziening.

Er zit geen "eindGeldigheid" op een product dat zichtbaar is (vanuit de relatie naar eindeGeldigheid van de lokale overheid). Ook kan je de catalogi en producten van beindigde gemeenten in principe voor eeuwig nog opvragen.

Moeten we die standaard uit de API resultaten filteren? Zorgt wel voor minder vervuiling.

**Comment by markbacker** [comment]
Het betreft hier gemeenten die bij de start van de invoervoorziening niet meer bestonden. Als we waren gestart met filtering van organisaties op einddatum zouden deze gemeenten (en catalogi) niet in de database zijn aangemaakt. Voor een schone start kunnen deze gemeenten en catalogi uit de invoervoorziening worden verwijderd. 

In #625 staat de vraag beschreven wat te doen met de life cycle van gemeenten en producten.

Niet meer updaten is niet echt een oplossing. Eerder beëindigde gemeenten zijn nog opvraagbaar, ook in productie. 
https://pdc.data.vng.nl/sdg/api/v1/organisaties?owmsPrefLabel=Zijpe is opvraagbaar, overigens wel met een owmsEndDate ingevuld

@joeribekker is verwijderen eenvoudig uit te voeren?

**Comment by joeribekker** [comment]
> Niet meer updaten is niet echt een oplossing. Eerder beëindigde gemeenten zijn nog opvraagbaar, ook in productie.
https://pdc.data.vng.nl/sdg/api/v1/organisaties?owmsPrefLabel=Zijpe is opvraagbaar, overigens wel met een owmsEndDate ingevuld

Volgens mij is dat op zich wel correct maar ik sta open voor suggesties. We kunnen ze ook blokkeren in de API, maar direct helemaal verwijderen lijkt me niet handig ivm eventueel overzetten van productteksten naar een andere gemeente. Echter, opschonen kan op termijn kan handig zijn.

> @joeribekker is verwijderen eenvoudig uit te voeren?

Op zich wel, maar nog nooit gedaan!

**Comment by joeribekker** [comment]
Ik heb nog geen antwoord op de vraag wat er nu moet gebeuren: 

A. Gemeenten en catalogi verwijderen
B. Gemeenten en catalogi niet meer teruggeven

**Comment by mrtn78** [comment]
ik ga voor optie B. verwijderen en opschonen is nu niet een prioriteit
