### ISSUE TITLE
Als redacteur wil ik een duidelijk herkenbare inlogpagina

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#409]
* [ ] Logo anders?
* [ ] Logo van YourEurope toevoegen?

**Comment by mrtn78** [comment]
tekstuele uitleg opnemen wat de voorziening is en waar deze voor is bedoeld

**Comment by mrtn78** [comment]
Dit is voorlopig duidelijk genoeg. Staat ook in de handleiding goed toegelicht.
