### ISSUE TITLE
Als redacteur wil ik op een duidelijke manier de gegevens van mijn organisatie(s) kunnen beheren

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#413]
* [x] Catalogi hernoemen naar Productenlijst

**Comment by svenvandescheur** [comment]
@vaszig are you able to pick this up? I invested and noticed that:

- We need to alter the view names
- The url namespace names
- Some file names
- Possibly other changes (labels etc.)

This is slightly more complicate than I expected.
