### ISSUE TITLE
Als redacteur wil ik direct duidelijk willen zien in welke taal ik bezig ben

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#415]
* [ ] tabblad is niet geprononceerd aanwezig

**Comment by FrankLieuwen** [comment]
kijken of dit nog actueel is na bevindingen kopgroep

**Comment by mrtn78** [comment]
Dit is verder meegenomen in issue #617 . Daarom is deze dubbel en kan worden gesloten.
