### ISSUE TITLE
Als redacteur wil ik helpteksten tot mijn beschikking hebben

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#416]
de helpteksten ontbreken

- [ ] 	- Als gebruiker wil ik op de pagina kunnen lezen wat er direct op deze pagina van mij verwacht wordt of wat er mogelijk is zodat ik een gevoel krijg vertrouwd te zijn met de voorziening en op de juiste plek de correcte handelingen verricht.
- [ ] 	- Als gebruiker wil ik een link naar de helpteksten en documentatie zodat ik bij twijfel nog meer context informatie kan inzien en doornemen om te leren wat de applicatie is, doet en wat ik er mee kan.

**Comment by FrankLieuwen** [comment]
kijken of dit nog actueel is na bevindingen kopgroep

**Comment by mrtn78** [comment]
dit issue is niet meer actueel
