### ISSUE TITLE
Als redacteur wil ik beschikken over een preview

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#418]
We hanteren het sjabloon zoals @markbacker dat heeft opgesteld in https://github.com/maykinmedia/sdg-invoervoorziening/issues/418#issuecomment-1090080154

### Userstory en uitgangspunten voor de preview

**User story**
Als redacteur wil ik een preview, opdat ik de volledige productbeschrijving (generiek en specifiek) tekstueel en de door mij gebruikte opmaak kan controleren en verbeteren

**Hoe roep je de preview op?**

edit pagina heeft 2 buttons
1. Preview concept (laatst opgeslagen)
2. Preview gepubliceerd

de preview biedt de mogelijkheid te switchen van taal
1. ~preview opent in de taal die redacteur bewerkt~ (kan niet ivm per veld switch)
2. toont 2 buttons EN en NL met getoonde taal actief

**Uitgangspunten voor sjabloon**
- gebruik als label voor de kopjes 
	- de teksten uit de **productfieldconfiguration**
	- in de volgorde van het sjabloon.
- Voor alle tekstblokken geldt
	- indien een tekstblok niet gevuld is, dan kop en tekst helemaal weglaten
	- uitzondering zijn *Titel gemeenteproduct titel* en de *specifieke tekst*. Zie uitleg in sjabloon

Tech tips
----

```
Taal: NL / EN
<hr>

<h3>{{ product_field_config.localizedgeneriekproduct_product_titel}}</h3>
{{ localized_generic_product.product_titel|markdownify }}
```

**Comment by markbacker** [comment]
Ayse en Wieke en ik werken aan een sjabloon, met daarin de labels van alle tekstblokken als kopjes. 
- Alle productbeschrijvingen moeten in dit sjabloon beschreven gaan worden. 
- en het sjabloon bepaalt de volgorde van de labels voor de edit-pagina en de preview.

Plek van de locatiegegevens, wordt vervolgd

**Comment by markbacker** [comment]
Behalve de plek van de locatiegegevens, moeten ook een plek voor de contactgegevens bepaald worden.

We hebben gesproken over twee preview-knoppen. Eén voor de concepttekst en één voor de gepubliceerde tekst.

**Comment by FrankLieuwen** [comment]
@markbacker we halen het niet om dit nog binnen de huidige sprint te realiseren.
Was ook al wel een tijdje bekend, vandaar dat ie prio M heeft gekregen.
Voor nu hebben we de handen vol aan de opleveren van een goedwerkende productie (inclusief bugfixes) omgeving met de functionaliteit zoals is opgenomen in de sprint.

**Comment by markbacker** [comment]
### Userstory en uitgangspunten voor de preview

**User story**
Als redacteur wil ik een preview, opdat ik de volledige productbeschrijving (generiek en specifiek) tekstueel en de door mij gebruikte opmaak kan controleren en verbeteren

**Hoe roep je de preview op?**

edit pagina heeft 2 buttons
1. Preview concept (laatst opgeslagen)
2. Preview gepubliceerd

de preview biedt de mogelijkheid te switchen van taal
1. preview opent in de taal die redacteur bewerkt
2. toont 2 buttons EN en NL met getoonde taal actief

**Uitgangspunten voor sjabloon**
- gebruik als label voor de kopjes 
	- de teksten uit de   **productfieldconfiguration**
	- in de volgorde van het sjabloon.
- Voor alle tekstblokken geldt
	- indien een tekstblok niet gevuld is, dan kop en tekst helemaal weglaten
	- uitzondering zijn *Titel gemeenteproduct titel* en de *specifieke tekst*. Zie uitleg in sjabloon

Zie volgende comment voor het sjabloon zelf

**Comment by markbacker** [comment]
Sjabloon voor de preview

# Ventvergunning `titel`

`generieke tekst`

# Informatie van de gemeente `Verantwoordelijke organisatie`

- indien `productAanwezig`is Nee, toon `productAanwezigToelichting` en verder niets
    
- indien `ProductValtOnder`is gevuld met productURI, toon `productValtOnderToelichting` en verder niets
    
- anders toon de specieke tekstblokken van gemeente in onderstaande volgorde
    

## Fruitkraam `titel`

Als de `titel` gevuld is, wordt deze altijd getoond (ongeacht of er een `specifieke tekst` is). Als `titel` leeg is, deze weglaten

`specifieke tekst`

## Voorwaarden

`vereisten`

## Nodig voor de aanvraag

`bewijs`

## Aanvragen

`procedureBeschrijving`

## Kosten en betalen

`kostenEnBetaalmethoden`

## Hoelang duurt het?

`uitersteTermijn`

## Bezwaar maken

`bezwaarEnBeroep`

## Wat te doen bij geen reactie

`wtdBijGeenReactie`

**[Button met tekst "Aanvragen bij gemeente" en daarachter de link `procedureLink`**

**Comment by markbacker** [comment]
Informatie die getoond wordt rechts van de productteksten

# Naast de generieke tekst
	
Laatst gecontroleerd op `laatstGecheckt`

#### Zie ook
- `links`
- `links`
- `links`

# Naast de specifieke tekst

#### Zie ook
- `links`
- `links`

#### Neem contact op met gemeente `VerantwoordelijkOrganisatie`
website [gemeente](contactgegevens.contactWebsite)
email: `contactgegevens.contactEmailadres`
telefoon: `contactgegevens.contactTelefoonnummer`

#### Waar kunt u dit product verkrijgen
`locaties.naam`
`straat` `nummer`
`postcode` `plaats`
Openingstijden:
  "maandag": [],
  "dinsdag": [],
  "woensdag": [],
  "donderdag": [],
  "vrijdag": [],
  "zaterdag": [],
  "zondag": []

`locaties.naam`
`straat` `nummer`
`postcode` `plaats`
Openingstijden:
  "maandag": [],
  "dinsdag": [],
  "woensdag": [],
  "donderdag": [],
  "vrijdag": [],
  "zaterdag": [],
  "zondag": []
