### ISSUE TITLE
Als beheerder wil ik locaties kunnen dupliceren

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#421]
1.	De demo toonde de locatie-gegevens, met de optie om meer locaties toe te voegen.
**Wens:** naast ‘toevoegen’ wil je ook locaties kunnen dupliceren
**Waarom?** Grotere gemeenten met een veelvoud aan locaties blijft zo een hoop dubbel werk bespaard: als de verdere gegevens grotendeels gelijk zijn (openingstijden), hoeft alleen het adres in de kopie(en) te worden aangepast. 

**Beter nog:** kopie locatie blijft voor diens openingstijden ‘kijken naar de originele invoer’ (invoerveld toont zo lang ook anders, voor visuele feedback dat dit centrale gegevens zijn) en pas bij handmatige aanpassing v.d. tijden toont dit weer als een normaal invoerveld, met die aangepaste tijden erin. 

Bij wijziging van de tijden voor de ‘hoofdlocatie’   gaat zo elke ongewijzigde kopie automatisch mee - dit scheelt ook in de toekomst werk.
(Wellicht ook handig: binnen dit scherm een knop ‘toon afhankelijke locaties’ o.i.d., zodat je alle locaties kunt controleren die (deze) gegevens delen met / lenen van deze locatie. 
(Wellicht ook een omgekeerde flow ‘toon parent’?)

**Onderhoudsvriendelijker met placeholders** 
(ipv allemaal individuele text fields) Want: als je alleen al Rotterdam en Amsterdam op een rijtje zet, incl. de verschillende stadswinkels valt op:
- Allebei hanteren openingstijden van 9-17u op ‘standaard dagen’ en van 9-20u op koopavond (in A’dam voor elk kantoor op donderdag, in R’dam voor elke locatie verschillend).  Verder is een enkele, kleine Rotterdamse stadswinkel bijv. maar 2 korte dagen open (afwijkende openingstijden + gesloten dagen) 

**Idee:** Centraal ingestelde tijden voor:

1. Opening regulier (in dit voorbeeld 9-17u)
2. Opening koopavond (in dit voorbeeld 9-20u)
 (al voor-ingevuld voor alle gemeenten, maar per gemeente natuurlijk aanpasbaar 1).

Laat vervolgens de voorziening voor elke werkdag < openingRegulier > tonen, **tenzij bij die dag**:
1.	  **Koopavond** is aangevinkt
2.	  **Gesloten** is aangevinkt, of
3.	Afwijkende tijden zijn ingevuld
 
**Complexiteit werkelijke data zelfs groter**
Bovenstaande gaat alleen nog maar om openingstijden – in de demo stónd ook alleen maar adres + openingstijden. Maar worden de opties nog uitgebreid, dan zou het heel goed kunnen zijn dat boven geschetste flexibiliteit voor die andere zaken óók wenselijk is. 

**Aanvullend: telefonische openingstijden + verdere contactmogelijkheden (14-xx)**
In de presentatie zag je alleen openingstijden + adres, maar op de eigen sites zie je naast de kantoor openingstijden (vb. stadskantoren Amsterdam) óók nog weer afwijkende openingstijden voor de telefonische bereikbaarheid (werkdagen van 8-18u), met een Bel-knop naar 14-020 én nog info over noodgevallen en Skype (nog los van het blokje ernaast over Mailen / contactformulier).

**Comment by FrankLieuwen** [comment]
kijken welke punten nog actueel zijn na bevindingen kopgroep

**Comment by mrtn78** [comment]
Dit is achterhaald nu alle locaties bijna zijn ingevuld
