### ISSUE TITLE
Als redacteur wil ik buitengewone openingstijden willen invoeren

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#422]
De demo liet een component zien waar ‘dé openingstijden’ in te bewerken waren. 
As is zou je dan de tijden voor feestdagen in de betreffende week live moeten aanpassen.

**Wens:** invoer v. feestdagen, zodat (nader te bepalen hoe lang) van tevoren bíj de reguliere openingstijden extra info wordt getoond over de aangepaste openingstijden, dan wel sluiting op die naderende feestdag(en).

**Comment by FrankLieuwen** [comment]
Het is mogelijk bijzonderheden toe te voegen aan de openingstijden van een locatie.
Uit de reacties kopgroep gemeenten moet blijken of dat afdoende is.

**Comment by mrtn78** [comment]
Er zijn geen verdere reacties uit de kopgroep en de ruim 200 nu aangesloten gemeenten gekomen over aanvullende wensen mbt openingstijden. daarom kan dit issue worden gesloten. het is achterhaald.
