### ISSUE TITLE
Als redacteur kom ik direct in de bewerk-modus van het product terecht (aanpassingen productpagina)

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#426]
* [x] #428
* [x] #427
* [ ] #429
* [x] #430
* [x] #431
* [x] #432
* [x] #433
* [x] #434
* [ ] #435
* [x] #436

**Comment by mrtn78** [comment]
De punten uit dit issue zijn grotendeels opgelost (8 van de 10) en de laatste 2 punten staan in de aankomende sprint op de planning. dit overkoepelende issue kan daarom worden gesloten.
