### ISSUE TITLE
Acties boven invoervelden verplaatsen

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#429]

**Comment by mrtn78** [comment]
ik zou de knoppen dubbel opnemen ipv verplaatsen

**Comment by joeribekker** [comment]
@FrankLieuwen Ik weet niet of deze UX wise nog steeds handig is

@svenvandescheur wat denk jij?

**Comment by svenvandescheur** [comment]
Hier kun je denk ik een "guternberg diagram" op loslaten:

![writgutenberg-diagram](https://user-images.githubusercontent.com/10243534/158569352-71103490-7f69-4d79-bc5b-47026d6ea9d7.png)

In principe wil je je primaire content (de tekst/teksteditor) linksboven. En je primaire actie (bewerken aanzetten) rechtsonder. Dit geeft ook het voordeel dat je er wat afstand tussen de knoppen van de teksteditor en de standaardtekst zit. Persoonlijk zou ik het zo laten.

**Comment by joeribekker** [comment]
@FrankLieuwen ik plaats deze na Svens reactie even buiten de sprint.

**Comment by FrankLieuwen** [comment]
check, verstandige keuze, is prima

Met vriendelijke groet,

*Frank Lieuwen*
projectleider dienstverlening
Tel: 0341411167




Op do 17 mrt. 2022 om 06:37 schreef Joeri Bekker ***@***.***>:

**Comment by FrankLieuwen** [comment]
Prio L gemarkeerd, wanneer dit bij de werkzaamheden van redactie naar voren komt kan alsnog worden overwogen hier iets mee te doen

**Comment by mrtn78** [comment]
Dit issue is niet meer relevant. er is ook geen feedback gekomen op dit aspect van de UX
