### ISSUE TITLE
Groter dan/kleiner dan tekens moeten toegestaan zijn (postproces iets)

### ISSUE THREAD

**Issue by FrankLieuwen** [maykinmedia/sdg-invoervoorziening#435]
Dit lijkt op ondersteuning voor: https://www.markdownguide.org/basic-syntax/#characters-you-can-escape

**Tasks**

* [x] Add support for `<` and `>` signs in text fields that support markdown.

**Comment by FrankLieuwen** [comment]
ter beoordeling volgende fase

**Comment by mrtn78** [comment]
dit lijkt nog niet helemaal goed te gaan. 
Deze input:
<test>
< dit is een tweede test >
Resulteert in deze preview:
\
\< dit is een tweede test >
zie ook: https://pdc-acc.vng.nl/sdg/organizations/147/productenlijst/2/products/33062/preview/

**Comment by joeribekker** [comment]
Created this issue to address the exact problem: https://github.com/maykinmedia/sdg-invoervoorziening/issues/848

Closing this one.
