### ISSUE TITLE
Als redacteur wil ik kunnen registreren dat in mijn gemeente een product valt onder ander product

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#439]
Voorbeeld is de terrasvergunning. Bij veel gemeenten valt de terrasvergunning onder de horecavergunning. In plaats van dat de gemeente aangeeft dat de terrasvergunning niet aanwezig is, wordt meegegeven dat de terrasvergunning valt onder de horecavergunning. 

De redacteur bewerkt product A. Bij deze gemeente wordt product A niet als zelfstandig product aangeboden, maar is het product onderdeel van een ander product, product B. De redacteur kan bij product A vastleggen dat dit product valt onder product B.

Hiervoor zijn in IM1.4 zijn de volgende attributen toegevoegd

| Attribuut (API)             | Label redactie     | Formaat |
| --------------------------- | ------------------ | ------- |
| ProductValtOnder            | Product valt onder | URI     |
| ProductValtOnderToelichting | Toelichting        | Tekstblok  |

Werking:
- op de edit-pagina onder algemene gegevens kan de redacteur aangeven dat het bewerkte product valt onder een ander product. Product B wordt met een pull down menu geselecteerd
  - Met een 'vink' geeft redacteur aan dat product valt onder ander product (default is leeg)
  - Als de 'vink' is gevuld, dan kan met de pull down het product worden geselecteerd
    - pull down toont gefilterde lijst van producten
    - in de pull down kan de redacteur 'zoeken' door eerste letters van product B in te typen
- Indien product valt onder ander product, dan moet de gemeente een toelichting voor op het portaal meegeven.
  - Onder de talen tabs wordt alleen het ProductValtOnderToelichting getoond, toelichting moet in Nederlands en Engels gegeven worden
  - Alle andere edit velden zijn niet meer zichtbaar, maar worden **niet** gewist
  - Ondersteuning redactie met standaard tekst, aanpasbaar door redacteur:
    - *In de gemeente {gemeente} valt de {producttitel} onder de {producttitel}*
- Specifieke teksten API
  - ProductValtOnder bevat de upnURI van product B (is leeg voor gewoon product)
  - ProductValtOnderToelichting bevat tekstblok
  - overige velden van product zijn leeg/weg?

Het portaal toont bij product A de toelichting met daarnaast een knop \[*ga naar {producttitel}*\]

**Comment by FrankLieuwen** [comment]
@joeribekker kun jij deze beoordelen?
Functionaliteit maakt onderdeel uit van toegezegde scope aan NP en zal vanuit dat oogpunt medio april beschikbaar moeten zijn,
