### ISSUE TITLE
Wijzigingen in specifieke teksten API

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#440]
In dit issue worden alle wijzigingen op de specifieke teksten API op een rijtje gezet.

Aanleidingen voor de wijzigingen:
- Oplevering generieke teksten API door DOP. 
  - De naamgeving en structuur van de attributen in beide API's is op elkaar afgestemd
- Nieuwe attributen in IM1.5
  - Product valt onder ander product
  - zie #439
- Ontbrekend attribuut
  - beschikbare talen ontbreekt
- Toegankelijk maken voor testen
   - zie #405 

De wijzigingen worden niet inhoudelijk in dit issue uitgewerkt. Deze zijn beschreven in [2022-02-17 Informatie model 1.5.xlsx](https://github.com/maykinmedia/sdg-invoervoorziening/files/8087587/2022-02-17.Informatie.model.1.5.xlsx). Zie sheet 'API mapping'

Nog in discussie:
- voor provincies en waterschappen de te realiseren specifieke teksten API minimaliseren
  - wat is de minimaal te realiseren API voor het publiceren van een specifieke tekst op het portaal?
  - Het portaal heeft voor het publiceren van een specifieke tekst niet alle resources nodig
    - producten voor de tekst en locaties
    - organisaties voor de contactgegevens (en deze wil DOP waarschijnlijk ook inline)
  - niet nodig zijn
    - catalogi
    - locaties (zijn inline beschikbaar)

**Tasks**

* [ ] Verwijder Organisatie.ondersteuningsorganisatie
* [ ]  Verwijder Producten.gerelateerdeProducten

**Opmerkingen:**

Producten.vertalingen.links.categorie wordt niet toegevoegd aan de API omdat deze ontbreekt in het IM
Producten.vertalingen.datumWijziging datum waarop de tekst is gewijzigd.

**Comment by mrtn78** [comment]
Dit is nu het informatiemodel versie 1.6 geworden

**Comment by joeribekker** [comment]
Voel je vrij om dit informatie model als bijlage toe te voegen aan dit ticket :)

**Comment by markbacker** [comment]
Bij deze dan het nog **niet vastgestelde** [Informatie model 1.6.xlsx](https://github.com/maykinmedia/sdg-invoervoorziening/files/9307575/Informatie.model.1.6.xlsx). In het PGI-overleg van 5 september wordt dit ingebracht ter vaststelling. Hierbij het 
[20220704 Verzoek tot wijziging 05 - 06 (2).docx](https://github.com/maykinmedia/sdg-invoervoorziening/files/9307650/20220704.Verzoek.tot.wijziging.05.-.06.2.docx) met daarin de beschreven de impact.

Deze versie bevat het logisch informatiemodel. De mapping met de API is uit het spreadsheet verwijderd, dit zorgde namelijk voor veel verwarring. Er zijn straks twee specificaties die op elkaar aansluiten:
- logisch informatiemodel voor afstemming in de keten
- OAS voor ontwikkelaars portalen en CMS leveranciers

Voor dit ticket is de mapping Informatiemodel - API nog wel relevant. In de sheet 'mapping' van  [Informatie model 1.6 API mapping.xlsx](https://github.com/maykinmedia/sdg-invoervoorziening/files/9307671/Informatie.model.1.6.API.mapping.xlsx) staan de verschillen tussen de huidige API en de te maken 1.6 versie. Ik denk dat het het handigst is om dit in een overleg door te lopen.

**Comment by mrtn78** [comment]
meenemen in de refinement voor sprint 9

**Comment by joeribekker** [comment]
Zolang er nog specs moeten komen graag bij VNG houden

**Comment by mrtn78** [comment]
gerelateerd aan issue #407

**Comment by joeribekker** [comment]
Even meenemen in de discussie:

SDU ziet NL en EN producten als verschillende producten met verschillende publicatiedatums. Dit werkt nu niet zo in de SDG invoervoorziening.

**Comment by mrtn78** [comment]
Afgesproken dat Joeri een afspraak maakt met Mark om dit te refinen

**Comment by joeribekker** [comment]
[Bijlage 2 - Informatie model 1.6.xlsx](https://github.com/maykinmedia/sdg-invoervoorziening/files/9567423/Bijlage.2.-.Informatie.model.1.6.xlsx)
[Bijlage 3 - Verzoek tot wijziging informatiemodel 1.5 - 1.6.docx](https://github.com/maykinmedia/sdg-invoervoorziening/files/9567424/Bijlage.3.-.Verzoek.tot.wijziging.informatiemodel.1.5.-.1.6.docx)

**Comment by joeribekker** [comment]
Op basis hiervan met @markbacker besproken:


IM 1.6

* [ ] Verwijder `Organisatie.ondersteuningsorganisatie`
* [ ] Verwijder `Producten.gerelateerdeProducten`

Opmerkingen:

* `Producten.vertalingen.links.categorie` wordt niet toegevoegd aan de API omdat deze ontbreekt in het IM
* `Producten.vertalingen.datumWijziging` datum waarop de tekst is gewijzigd.
