### ISSUE TITLE
Hoe kan ik in het API-interface van de SDG zien of in tekstvelden markdown is gebruikt?

### ISSUE THREAD

**Issue by HenriKorver** [maykinmedia/sdg-invoervoorziening#441]
@joeribekker Je zou een extra boolean attibute verwachten dat aanduidt of in het textveld wel of niet markdown als format is toegepast of zoiets dergelijks.

**Comment by joeribekker** [comment]
Hmm, kan, maar ik vermoed echter dat we dit beter als uitleg bij het veld kunnen toevoegen omdat dit ook geen keuze is die redacteuren kunnen aangeven. Er ligt dus van te voren vast welke velden markdown bevatten en welke niet.

**Comment by HenriKorver** [comment]
Aha, bij jullie ligt het natuurlijk al van te voren vast welke velden markdown bevatten, helder. Wel fijn natuurlijk als dat bij de uitleg van de velden in de OAS wordt toegevoegd.

**Comment by joeribekker** [comment]
Zeker, dus goed ticket!

**Comment by joeribekker** [comment]
De documentatie van de API is ondertussen bijgewerkt en bij Markdown velden staat dit expliciet aangegeven.

Van mij mag het ticket daarom gesloten worden.
