### ISSUE TITLE
Als redacteur wil ik op de bewerkpagina toelichtende teksten die duidelijk maken wat ik zie of bewerk

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#442]
Dit issue kwam naar boven in een sessie met de GGR redacteuren over labels en tooltips. Weliswaar een andere sessie, maar deze hoort bij label 'Feedback UX sessie' .

Bij het schrijven van de labels en tooltips kwam naar boven dat nu in iedere tooltip telkens weer contextuele informatie nodig is. Het is veel duidelijker als dit in de blokken algemeen, generiek en specifiek direct te lezen is

Wensen
- de headings zoals 'Algemene Gegevens | Huidige Informatie' ook opnemen in pagina met te wijzigen labels
- onder een heading kan een toelichtende tekst worden getoond
  - bijv. onder generieke gegevens 'Je ziet hier de tekst van Ondernemersplein of Rijksoverheid' 
  - etc.

Extra wens
- op basis van de doelgroep van het product kan een andere tekst worden getoond
  - bijv. onder generieke gegevens 'Je ziet hier de tekst van {Ondernemersplein|Rijksoverheid}'

**Comment by FrankLieuwen** [comment]
Evt opnemen als vervolg in volgende fase

**Comment by joeribekker** [comment]
@mrtn78 Willen we dit echt? We hebben toch de (i)-tooltip?

**Comment by mrtn78** [comment]
ik kan dit zelf niet echt inschatten. ben niet bij de UX sessie geweest. Wat vind jij hiervan @markbacker ?

**Comment by mrtn78** [comment]
De prio is aangepast naar Low en voorlopig willen we dit dus nog niet ;-)

**Comment by mrtn78** [comment]
inmiddels hebben we een uitstekende handleiding en implementatie adviseurs die dit toelichten indien het nog niet duidelijk is. Ik sluit het issue dus omdat het a. achterhaald is door de handleiding en b. niet meer gerelateerd is aan gebruikers wensen
