### ISSUE TITLE
De specifieke teksten API ontsluit alleen de gegevens zoals afgesproken in het SDG informatiemodel

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#445]
De specifieke teksten API ontsluit meer gegevens dan in het SDG informatiemodel is afgesproken. Dit kan worden opgelost door naast de huidige API een tweede specficatie te maken die exact aansluit op het SDG informatiemodel.

Deze SDG IM conforme API zal wat compacter zijn. 
- geen resource catalogi
- eventueel resource locaties verwijderen (worden immers inline meegegeven)

De SDG IM conforme API is met name van belang voor provincies en waterschappen. Anders zouden deze partijen ook een implementatie met catalogi moeten bouwen, terwijl dat voor SDG geen vereiste is.

**Comment by markbacker** [comment]
@joeribekker Issue gevonden!

In de nieuwste versie van het [Informatie model 1.6.xlsx](https://github.com/maykinmedia/sdg-invoervoorziening/files/8428299/Informatie.model.1.6.xlsx) is in de sheet "API mapping" uitgewerkt hoe de SDG specifieke teksten API eruit moet zien. 

Attribuutnamen zijn afgestemd met DOP (Elie)

We bespreken nog wat dit betekent voor de volledige API en hoe deze naast elkaar bestaan.

**Comment by joeribekker** [comment]
@markbacker Ik weet alleen niet wat we er in dit stadium mee moeten doen

**Comment by mrtn78** [comment]
in de werkgroep Techniek besproken en het is niet erg dat er extra resources in de API staan. Dit geeft geen problemen bij alle stakeholders.
