### ISSUE TITLE
Als VNG wil ik de tekst voor de uitnodigingse-mail anders hebben

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#448]
Graag tekst aanleveren die veschijnt in de uitnodigingsmail.

**Comment by FrankLieuwen** [comment]
@markbacker kun jij de betreffende tekst 'ophalen' bij de redacteuren?

**Comment by markbacker** [comment]
Hieronder het tekstvoorstel dat ik heb gevraagd aan Douwe. Steven heeft meegelezen.

Er staan nog 2 punten open:
- Hoe lang is de activerings-link geldig? En wat zijn overwegingen om deze periode in de mail te vermelden.
- Het emailadres voor vragen over het inloggen moet nog ingevuld. Dit volgt nog.

---

**Onderwerp: Activeer uw account invoervoorziening SDG voor gemeenten**

Beste *Naam*,

Hartelijk dank voor het aanmelden bij de invoervoorziening Single Digital Gateway (SDG) voor gemeenten. U heeft zojuist toegang gekregen.

**Activeer nu uw account**
Met de onderstaande link stelt u uw account in en leest u de instructies op onze website:

https://pdc.vng.nl/sdg/invitation/97iTe4UlUosT

Met uw account heeft u toegang tot de invoervoorziening en de teksten die ter controle voor uw organisatie klaarstaan.

**Heeft u vragen?**
Heeft u vragen over de invoervoorziening? Op de [Pleio omgeving van SDG](https://werkenaaneenoverheid.pleio.nl/groups/view/ed87e451-f6fc-49b0-aec4-41f2358426f7/single-digital-gateway) vindt u informatie en handleidingen. Heeft u andere vragen? Neem contact met ons op via \[e-mail\].

Met vriendelijke groet,

Programmateam Single Digital Gateway
VNG Realisatie

Dit bericht is automatisch aangemaakt en verstuurd. U kunt hier niet op antwoorden.

**Comment by joeribekker** [comment]
Terug assigned vanwege openstaande punten

**Comment by FrankLieuwen** [comment]
sdg@vng.nl
activeringslink voor nu twee weken, graag opnemen in bevestigingsmail
@markbacker ga jij hiermee shoppen?

**Comment by FrankLieuwen** [comment]
Onderwerp: Activeer je account invoervoorziening SDG gemeenten

Beste _Naam_,

Hartelijk dank voor het aanmelden bij de invoervoorziening Single Digital Gateway (SDG) voor gemeenten. Je hebt zojuist toegang gekregen.

**Activeer nu jouw account**
Met de onderstaande link stel je jouw account in en lees je de instructies op onze website.

https://pdc.vng.nl/sdg/invitation/97iTe4UlUosT

Let op: je hebt 2 weken de tijd om je account te activeren.

Met jouw account heb je toegang tot de invoervoorziening. Ook kun je hier de teksten controleren en aanvullen met informatie van jouw gemeente. 

**Heb je vragen?**
Op de [Pleio omgeving van SDG](https://werkenaaneenoverheid.pleio.nl/groups/view/ed87e451-f6fc-49b0-aec4-41f2358426f7/single-digital-gateway) vind je informatie en handleidingen voor de invoervoorziening. Heb je andere vragen? Stuur een e-mail naar [sdg@vng.nl].

Met vriendelijke groet,

Programmateam Single Digital Gateway
VNG Realisatie

Dit bericht is automatisch aangemaakt en verstuurd. Je kunt hier niet op antwoorden.
