### ISSUE TITLE
Pressing Enter should not save the text

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#450]
When pressing enter on a charfield, the form submits... it should not.

Can be done by simply not defining a `<button type=submit>` button (but just a butten-element).

**Comment by FrankLieuwen** [comment]
ter beoordeling volgende fase

**Comment by joeribekker** [comment]
@bart-maykin Wellicht kan dit door geen default-button te definieren op het formulier.
