### ISSUE TITLE
Tekst vergelijken en daarna aanpassen blijft versies tonen tijdens edit weergave

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#453]

**Comment by mrtn78** [comment]
De knoppen blijven ook bold na het wisselen van de view "toon standaard tekst". zie ook:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/1629141/170943168-6e20b7f5-9bd6-45f0-acd0-c81a7870a93d.png">
