### ISSUE TITLE
API op test redirect naar invoervoorziening

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#458]
Melding van Elie van DOP

Als ik bijv. https://sdg-invoervoorziening.maykin.nl/api/v1/producten aanroep dan wordt ik geredirect naar de invoervoorziening zelf
Acceptatie en productie API urls zijn wel bereikbaar.

**Comment by joeribekker** [comment]
De URL is aangepast tbv definitieve endpoints op acceptatie en prod. We staat nu /sdg voor: https://sdg-invoervoorziening.maykin.nl/sdg/api/v1/producten
