### ISSUE TITLE
Bug: kan gebruiker niet aan gemeente Amsterdam koppelen

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#460]
Bij het aanmaken van een account voor Ayse op acceptatie en productie kan ik haar niet koppelen aan de gemeente amsterdam. 

Amsterdam bestaat wel in de OWMS lijst, maar is niet zichtbaar bij het aanmaken van een account
![image](https://user-images.githubusercontent.com/41415562/157013163-8b60fb74-0d12-40f7-be06-ed7bdb7610e5.png)

**Comment by joeribekker** [comment]
Productie issues graag melden op Taiga
