### ISSUE TITLE
Bij aanmaken gebruiker testomgeving geen aanmeldingsmail

### ISSUE THREAD

**Issue by Douwewal** [maykinmedia/sdg-invoervoorziening#461]
Mark heeft voor mij een account aangemaakt voor de testomgeving. Er kwam geen aanmeldingsmail binnen (ook niet in ongewenst). Ook wachtwoord resetten werkt dan niet omdat er nog geen wachtwoord is. Blijkbaar blijven de mails ergens hangen?

We hebben het (tijdelijk) opgelost door de inloggegevens aan te maken en te delen met mij.

**Comment by joeribekker** [comment]
Dit is een configuratie dingetje. Ondertussen zou dat opgelost moeten zijn.
