### ISSUE TITLE
Als redacteur wil ik de invoervelden in een goed lezen volgorde zien

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#468]
Zet de velden en tekstblokken in de edit-pagina in de goede volgorde.

De volgorde is gedefinieerd in de labels in de testomgeving met een nummer als prefix.

**Comment by FrankLieuwen** [comment]
@joeribekker hoeveel werk is dit? Het gaat om het aanpassen van de volgorde van de invoervelden.
Mark geeft aan dat de behoefte van redactie hierbij hoog is, graag eerst een haalbaarheidsoordeel voor evt huidige sprint.

**Comment by joeribekker** [comment]
Niet veel werk, max een uurtje.

**Comment by FrankLieuwen** [comment]
@joeribekker top dank, zie dat je hem al in de sprint hebt gezet
