### ISSUE TITLE
logging deleted after deleting product version

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#484]
As 'beheerder' I dont want to delete the "logboekvermelding" after deleting the product version in the admin interface. All cCUD transactions must retain visible in the "logboekvermelding"

**Comment by joeribekker** [comment]
Dit is geen bug maar (nu eens echt) working as intended en onderdeel van het onderliggende  framework.  Wijzigingen hierop is dus een verbetering.

**Comment by joeribekker** [comment]
So, we need to retain "logboek" entries when a productversion is deleted.

@dariomory do you see any possibilities to do this? Can you discuss this with Alex?
