### ISSUE TITLE
Fixes required for list page

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#487]
**Product list page**

* [x] The list queryset is not properly created: It doesn't contain "reference" products. We discussed that we would initialize the list upon "some trigger" TO DISCUSS (!)
* [x] Columns should include "doelgroep"

@svenvandescheur :

* [x] Sticky pagination should be fixed, or just non-sticky/absolute (FIX: Make unsticky)
* [x] Global filter textfield should be white to indicate you can type things there (FIX: make white)
* [x] Space on the sides of the list component should be removed (padding van de eerste en laatste kolom van datagrid)

**Comment by svenvandescheur** [comment]
> Sticky pagination should be fixed, or just non-sticky/absolute (FIX: Make unsticky)
 
 An earlier fixed improved the way this currently works, so I'm marking this as resolved. If we still want to make it unstick please open a new issue.
