### ISSUE TITLE
Using standard text uses the wrong text version

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#502]
![image](https://user-images.githubusercontent.com/96970/161273703-f3e3fd34-d3c6-4767-a42c-66c3c7a71411.png)

I think the JS references the wrong text element (previous-version, instead of current-version).

**Comment by bart-maykin** [comment]
I cant seem to replicate this issue, on the current master branch it fills in the correct text

**Comment by joeribekker** [comment]
I think Sven fixed this.
