### ISSUE TITLE
Adding a user in production results in a error

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#509]
Invite_user: (550, b'The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements')

De gebruiker '[Martin Test van der Plas Test](https://pdc.vng.nl/sdg/admin/accounts/user/24/change/)' is met succes toegevoegd. U kunt deze hieronder weer bewerken. Link: https://pdc.vng.nl/sdg/admin/accounts/user/24/change/

<img width="1614" alt="Screenshot 2022-04-05 at 14 36 09" src="https://user-images.githubusercontent.com/1629141/161755279-cd72856c-7e73-451d-9282-18e40bdc5a7b.png">

**Comment by mrtn78** [comment]
Probably related to #403

**Comment by joeribekker** [comment]
Dit is mijn fout geweest en betreft een configuratie fout in de recente uitrol. Wordt vandaag gecorrigeerd.

**Comment by joeribekker** [comment]
Opgelost.
