### ISSUE TITLE
Spoed: titel veld van een generieke én specifieke tekst is te kort

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#510]
Melding van DPC redacteur:

Bij het invoeren van de NL-tekst ondervond ik geen problemen. Máár, bij de EN-tekst kon ik niet de volledige producttitel invoeren. Deze wordt namelijk bij het laatste woord afgebroken. Het lijkt erop dat je op dit moment bij de producttitel van de EN-tekst maar een beperkt aantal tekens mag invoeren. 

> Even uitgeprobeerd. De `titel` is begrenst op 50 karakters. Dit is te kort voor sommige producttitels
> dit geldt voor zowel de titel van een generieke tekst als voor een specifieke tekst.

Graag de `titel` van de zowel generieke als specifieke tekst onbeperkt maken of zodanig verlengen dat een producttitel hier altijd zal inpassen.

**Comment by FrankLieuwen** [comment]
@joeribekker iets voor op de bug list?

**Comment by joeribekker** [comment]
Buglist klinkt niet als een scrum event ;-)

Dit kan wel mee. Klinkt als volgende sprint, officieel gezien. Vandaar dat deadlines en testen niet zo dicht op elkaar moeten zitten..

**Comment by joeribekker** [comment]
Onbeperkt lijkt me communicatief EN user interface-wise een slechte keuze.

@bart-maykin Kan jij deze kolom ophogen naar 100 characters?
