### ISSUE TITLE
meerdere SDG Thema's tonen in de productenlijst

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#512]
Wanneer een product meerdere SDG codes heeft wil ik deze terugzien in de productenlijst waarin alle producten staan en ook bij het sorteren en filteren de producten in meerdere views terugzien. producten moeten niet meerdere keren voorkomen op de productenlijst.

* [x] #792

**Comment by joeribekker** [comment]
Ik wil eerst horen hoe VNG dit in een lijst weergave wilt zien, rekening houden met kolombreedtes

**Comment by mrtn78** [comment]
> Ik wil eerst horen hoe VNG dit in een lijst weergave wilt zien, rekening houden met kolombreedtes

Graag meerdere SDG thema's onder elkaar tonen.
