### ISSUE TITLE
[NF-17] Performance

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#53]
De performance eisen worden gemeten in de gebruikers acceptatietest.

**Comment by mrtn78** [comment]
Zie ook https://vvng.sharepoint.com/:p:/r/sites/SingleDigitalGateway/Gedeelde%20documenten/General/Realisatie%20Invoervoorziening/20211108%20keten%20testen.pptx?d=w243afbd089ae4e4bacd9d193b0e89e5e&csf=1&web=1&e=aIcfFU
