### ISSUE TITLE
Fix styling in editor panels

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#534]
Current:
![image](https://user-images.githubusercontent.com/96970/162762305-e1e138e4-972c-4087-9717-3b8d33b05e25.png)

How it should be:
![image](https://user-images.githubusercontent.com/96970/162762356-207cbf50-2eb4-46b4-9134-45910f78e720.png)

**Comment by markbacker** [comment]
Ook gek is het verschil tussen styling specifieke tekst en de standaardtekst. Zie sceenshot hieronder, waar in beide teksten de bullets aan staan.

![image](https://user-images.githubusercontent.com/41415562/163130689-f5a4a1b0-f17c-4af1-871c-908a2fab48e7.png)

Screenshot is van https://sdg-invoervoorziening.maykin.nl/sdg/organizations/2/productenlijst/2/products/351/edit/
