### ISSUE TITLE
Bevindingen productenlijst filter aanwezig

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#536]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

Filteren op aanwezig werkt nu niet. 

Het filter en de waarden zijn niet compleet. Het filter moet gelijkwaardig zijn aan de status-knoppen die we eerst hadden.

### Stappen om te reproduceren / Steps to reproduce

https://sdg-invoervoorziening.maykin.nl/sdg/organizations/2/productenlijst/

### Verwacht gedrag / Expected behavior

Titel filter: status
Mogelijke waarden: Aanwezig, Niet aanwezig, Controle nodig, Niet gepubliceerd.

Kiezen van een waarde filtert de lijst

**Comment by joeribekker** [comment]
@markbacker Je hebt 2 dingen hier gecombineerd. De bug is ondertussen opgelost: Je kan filteren.

Het wijzigen van de kolommen, en het toevoegen van een status is zoals besproken lastiger omdat hierin verschillende dingen tot uiting komen en middels kolommen anders werkt.

Omdat hier het label bug aan hangt sluit ik het ticket want de bug is opgelost. Als de redacteuren andere kolommen willen dan zie ik dat in een nieuw ticket wel tegemoet.
