### ISSUE TITLE
Productenlijst filter doelgroep

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#537]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

Filter doelgroep werkt, maar zou een keuze uit twee waarden moeten tonen

### Stappen om te reproduceren / Steps to reproduce

https://sdg-invoervoorziening.maykin.nl/sdg/organizations/2/productenlijst/?_name=&referentie_product__generiek_product__upn__thema__informatiegebied=&product_aanwezig=&doelgroep=bedrijf

### Verwacht gedrag / Expected behavior

Filter: Doelgroep
Mogelijke waarden : eu-burger, eu-bedrijf

**Comment by joeribekker** [comment]
Dit is naar mijn mening geen bug, maar een verbetering: Immers, zoeken op "burg" resulteert in een lijst met enkel "eu-burger".

**Comment by FrankLieuwen** [comment]
ter beoordeling volgende fase

**Comment by joeribekker** [comment]
Dit is opgelost in 1.2.3
