### ISSUE TITLE
Bug en verbeteringen "product valt onder"

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#540]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

Bugs
- eerst geselecteerde product wordt gebruikt voor het aanmaken van de vooringevulde `productValtOnderToelichting`

Te verbeteren
- dropdown list `productValtOnder` is niet gesorteerd sortering
- `productValtOnderToelichting` staat helemaal onderaan het formulier, lang scrollen

### Verwacht gedrag / Expected behavior

Bug:
- als `productValtOnder` is gewijzigd, dan wordt een nieuwe tekst `toelichtingproductValtOnder` gegenereerd

Verbetering
- dropdown `productValtOnder` is alphabetisch gesorteerd
- als een `productValtOnder`  product is gekozen, wordt alleen het veld `productValtOnderToelichting` getoond. De overige velden zijn immers niet relevant (zat ook in originele ticket)

**Comment by joeribekker** [comment]
Dit zijn geen bugs maar verbeteringen.

Er is expliciet gekozen om, als er tekst staat, deze niet bij te werken (wat het geval is na de eerste keuze) zodat niet een eigen tekst overschreven wordt.

Een klein deel wordt getackled in #548

**Comment by FrankLieuwen** [comment]
ter beoordeling volgende fase

**Comment by mrtn78** [comment]
Na testen lijkt het erop dat de tekst niet volledig wordt gecreëerd bij de optie product valt onder.
bij het maken van een screenshot met een ander product leert de ervaring dat eerst de titel van het product bekend moet zijn om de creatie van de algemene gegevens goed te laten verlopen. ik heb het ticket daarom weer gesloten.
