### ISSUE TITLE
NL|EN wijzigt niet de generieke tekst

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#542]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

Als bovenin de edit-pagina de taal op EN wordt gezet, blijft de generieke tekst NL

### Stappen om te reproduceren / Steps to reproduce

https://sdg-invoervoorziening.maykin.nl/sdg/organizations/2/productenlijst/2/products/54042/edit/

Klik bovenin op EN, generieke tekts van de terrasvergunning wordt niet getoond.

### Verwacht gedrag / Expected behavior

Alle teksten switchen naar EN

**Comment by joeribekker** [comment]
Duplicate van #532
