### ISSUE TITLE
Productenlijst sortering informatiegebieden

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#543]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

Dropdown voor filtering informatiegebied is niet gesorteerd

![image](https://user-images.githubusercontent.com/96970/167372845-7c228c0e-ded6-405e-ac58-47ee9536d130.png)

### Stappen om te reproduceren / Steps to reproduce

https://sdg-invoervoorziening.maykin.nl/sdg/organizations/3/productenlijst/?ordering=-_name

### Verwacht gedrag / Expected behavior

dropdown gesorteerd

**Comment by joeribekker** [comment]
Geen bug, maar verbetering.

**Comment by FrankLieuwen** [comment]
ter beoordeling volgende fase
