### ISSUE TITLE
Editor met subopsommingen

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#551]
### Thema / Theme

CMS

### Omschrijving / Description

De invoerders hadden de onderstaande punten over de editor.
-	Subopsommingen binnen een opsomming kan niet.

Oplossing zou zijn om inspring knoppen toe te voegen 
![image](https://user-images.githubusercontent.com/41415562/163113823-64b064e4-204e-443c-8f93-52da7916e849.png)

### Added value / Toegevoegde waarde

Bestaande teksten met subopsommingen kunnen in dezelfde opmaak ingevoerd worden.

**Comment by markbacker** [comment]
Wieke gaat bijhouden in welke productteksten meerdere niveau's opsommingen voorkomen. 

Op basis hiervan bepalen wat de prioriteit is

**Comment by joeribekker** [comment]
Ik zie dat dit kan met de gebruikte library, dus technisch zal het niet de wereld zijn: https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html
