### ISSUE TITLE
Productversies worden niet meer getoond

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#553]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

Met het verdwijnen van de detail-pagina wordt de versie-history van een producttekst niet meer getoond

### Verwacht gedrag / Expected behavior

Toon de versie-history onder de edit-pagina

**Comment by joeribekker** [comment]
Hmm, geen bug maar verbetering.

Er was al besloten om detail pagina te laten vervallen. Ik zet em even onderaan de prio lijst.

**Comment by joeribekker** [comment]
Gaat om dit terug zetten, maar dan onderaan de edit-pagina. Vermoed dat het fijn is als het onder een zelfde kopje valt als "Algemene gegevens", genaamd "Geschiedenis" die standaard ingeklapt is:

Zie: https://github.com/maykinmedia/sdg-invoervoorziening/blob/1.0.0/src/sdg/templates/producten/detail.html#L136

Mind the css.

**Comment by markbacker** [comment]
Prima voorstel! Dan staan de versies dicht bij de publicatiedatum van de actuele tekst. Inklappen is daar zeker nodig, anders schuift de tekst wel erg ver naar onderen.
