### ISSUE TITLE
Loze vergrendelknop bij locatie openingstijden

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#555]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

Ongeacht stand vergrendeling kan je de openingstijden editen
![image](https://user-images.githubusercontent.com/41415562/163133370-90d33c29-7df4-4730-9a34-743732b0f3a3.png)

### Stappen om te reproduceren / Steps to reproduce

zie https://sdg-invoervoorziening.maykin.nl/sdg/organizations/2/locaties/

### Verwacht gedrag / Expected behavior

Geen vergrendelknop

**Comment by joeribekker** [comment]
Ja, dit is inderdaad een bug. Duplicate van #519
