### ISSUE TITLE
label en tooltip voor productValtOnder en bevoegdeOrganisatie

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#559]
### Product versie / Product version

release 11-4

### Omschrijf het probleem / Describe the bug

onduidelijk label en geen tooltip bij productValtOnder en bevoegdeOrganisatie

![image](https://user-images.githubusercontent.com/41415562/163136144-5a10a8c4-740e-4cc9-8c07-a79bb80dea04.png)

### Verwacht gedrag / Expected behavior

Met de pagina [Product field configuratie](https://sdg-invoervoorziening.maykin.nl/sdg/admin/core/productfieldconfiguration/) kunnen voor  productValtOnder en bevoegdeOrganisatie een label en een tooltip beheerd worden.

**Comment by FrankLieuwen** [comment]
eerst gemarkeerd als bug, toen weer niet
even consensus zoeken ;-)
