### ISSUE TITLE
Productenlijst kolom aanwezig => aangeboden

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#565]
### Thema / Theme

CMS

### Omschrijving / Description

De productenlijst heeft nu een kolom met het label Aanwezig. Dit is verwarrend.
Reactie van Wieke
> Ik denk namelijk bij Aanwezig of het product aanwezig is in de invoervoorziening. Maar niet of het product aangeboden wordt door de gemeente. Ik zou erbij zetten: Aangeboden door jouw gemeente. Oid.

Verbetering
- Kolom label wordt “Aangeboden”. Op de edit-pagina moeten dan het label en tooltip omgewisseld worden. Dit kunnen we zelf met de configuratiepagina
- De waarden waarop je kunt filteren moeten gelijk zijn aan die op de edit pagina, en dus [onbekend, ja, nee]

Wel mooi dat in de kolom groene vinken en rode kruizen worden getoond. Houden zo

### Added value / Toegevoegde waarde

Geen verwarring

**Comment by FrankLieuwen** [comment]
binnengekomen na sluiting sprint 7 en preview
mogelijk opnemen in volgende fase
