### ISSUE TITLE
Regressie; error 500 productfieldconfiguration

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#575]
### Product versie / Product version

20 april

### Omschrijf het probleem / Describe the bug

Openen https://sdg-invoervoorziening.maykin.nl/sdg/admin/core/productfieldconfiguration/ geeft error 500

**Comment by joeribekker** [comment]
Even op het board kijken graag, deze was nog niet opgelost. Zie: #557
