### ISSUE TITLE
Gebruiker koppelen aan Utrecht (Utr)

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#581]
### Product versie / Product version

21-4

### Omschrijf het probleem / Describe the bug

Er zijn 2 gemeenten Utrecht

### Stappen om te reproduceren / Steps to reproduce

Bij het aanmaken van een account voor Utrecht kon ik kiezen uit 
- Utrecht en 
- Utrecht (Utr)

Onder organisaties zag ik dat Utrecht (Utr) een einddatum
![image](https://user-images.githubusercontent.com/41415562/164485501-1d500367-3411-4408-8b26-dc2d6284dcf1.png)

### Verwacht gedrag / Expected behavior

Eén gemeente Utrecht om uit te kiezen.

Ik heb gekozen voor Utrecht, zonder einddatum

**Comment by FrankLieuwen** [comment]
Volgens mij moet hier duidelijk worden welk soort organisatie het betreft (gemeente/provincie/waterschap)
