### ISSUE TITLE
Got attribute error when attempting to get value for field upn_uri

### ISSUE THREAD

**Issue by bart-maykin** [maykinmedia/sdg-invoervoorziening#583]
![Screenshot from 2022-04-22 09-15-36](https://user-images.githubusercontent.com/101265650/164626245-e4e4a9fe-87b8-49dc-8af6-e3179fe06639.png)
![Screenshot from 2022-04-22 09-20-42](https://user-images.githubusercontent.com/101265650/164626338-87b52aea-31cb-4ea6-a999-f6ac2fd95c8e.png)

**Comment by joeribekker** [comment]
Fixed in 1.2.2 (or did not occur ever since.).
