### ISSUE TITLE
Add ordering on all models

### ISSUE THREAD

**Issue by bart-maykin** [maykinmedia/sdg-invoervoorziening#597]

**Comment by mrtn78** [comment]
hi @joeribekker kan je toelichten wat dit issue inhoud, waarom het geen prio heeft maar wel een VNG issue is?
wat mij betreft mag deze worden gesloten.

**Comment by joeribekker** [comment]
Dit ticket was te groot ingezet maar het doel was om ordering van API resultaten expliciet toe te voegen anders kan paginering raar gaan.

Dit moet even gecontroleerd worden in de API of het voor alle resources is gedaan.

**Comment by joeribekker** [comment]
Besloten dit opnieuw te bekijken als het nodig is.
