### ISSUE TITLE
‘Url aanvraagformulier’ werkt niet in preview

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#608]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

Link wordt idd niet weergegeven, Wieke heeft dit getest. Reproduceerbaar door de link toe te voegen en de preview te openen. De link wordt niet getoond.

### Verwacht gedrag / Expected behavior

De verwachting is dat de link ook in de preview wordt getoond.

**Comment by bart-maykin** [comment]
Klopt het dat het over dit veld gaat?
![Screenshot from 2022-05-16 14-55-08](https://user-images.githubusercontent.com/101265650/168764719-9ff49dfe-8e62-4c58-86a0-970d519bf435.png)

Want als dat klopt dan is die te zien op de preview pagina boven aan de rechter kant
![Screenshot from 2022-05-17 10-16-15v2](https://user-images.githubusercontent.com/101265650/168766137-b341c492-24b6-402c-ac9f-37e1ca4fdb36.png)
