### ISSUE TITLE
locaties en gebruikersbeheer niet zichtbaar

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#611]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

Ik heb mijn collega Fatima van Kollenburg-Chenti beheerder gemaakt voor zowel Boxtel als Sint-Michielsgestel. Zij ziet helaas de andere opties zoals ‘locaties’ en ‘gebruikersbeheer’ nog steeds niet. Kunnen jullie dit voor ons nakijken?

Gebruiker gemaild met de vraag of ze een screenprint kan maken, instellingen staan goed!? Even navragen bij Mark/Martin (MOGELIJK EESR GEMEENTE KIEZEN)

### Verwacht gedrag / Expected behavior

Wanneer een gebruiker nog geen organisatie heeft gekozen dan aangeven dat er eerst ee norganisatie moet worden gekozen voordat men de gegevens van de organisatie kan wijzigen.

**Comment by RobbieZ69** [comment]
Hoi Martin,
Zoals ik in de mail al aangaf, kan deze gesloten worden het is met de gebruiker al opgelost. Was een gebruikersfout.

gr. Rob

**Comment by mrtn78** [comment]
hi Rob, ik heb m laten staan zodat we voor deze exception een melding of tooltip op het scherm kunnen tonen. Als gebruiker verwacht je een bepaalde actie en er is geen response. dat zorgt voor vragen en een simpele response met de melding dat je eerst een organisatie moet selecteren helpt gebruikers verder. vandaar dat ik m toch heb opgevoerd als bug en laat staan in de lijst.

**Comment by joeribekker** [comment]
Ik sluit deze en maak er een improvement van.
