### ISSUE TITLE
Preview button

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#616]
### Thema / Theme

CMS

### Omschrijving / Description

De huidige link naar de preview functie wordt niet gezien/gevonden door redacteuren.
Ook is het voor redacteuren onduidelijk wat het verschil is tussen het laatst opgeslagen concept en de laatst gepubliceerde versie.

Voorgestelde oplossing:
- Er is 1 duidelijke preview button, de button heet 'preview'
- De preview button is onderin de pagina altijd zichtbaar naast de buttons voor opslaan en publiceren
- De preview toont de laatst opgeslagen producttekst, ongeacht of dit een concept is of een (zojuist) gepubliceerde tekst

### Added value / Toegevoegde waarde

Een goed vindbare preview functie die altijd de laatst opgeslagen tekst toont

### Aanvullende opmerkingen / Additional context

Graag inschatten hoeveel werk het is om ook preview buttons achter de oude versies te tonen. 

Op basis van de hoeveelheid werk kunnen we dan bepalen of we deze optie nu willen meenemen

**Comment by mrtn78** [comment]
Zie ook : https://github.com/maykinmedia/sdg-invoervoorziening/issues/617#issuecomment-1238187278
