### ISSUE TITLE
[CMS-SDG-3] CMS eisen (3)

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#62]
- Het beheer van de content kan als functionaliteit ook via een API worden ontsloten.
- Een standaard eindgebruiker website wordt gehost om direct de aangepaste content in een live omgeving te tonen. Bijvoorbeeld op sdg.vng.nl (zie #22 voor preview functie)
- Gebruikers authenticatie en identificatie moet kunnen op basis van bestaande IAM voorzieningen

**Comment by mrtn78** [comment]
punt 2 en 3 zijn bijkomende aandachtspunten als punt 1 wordt uitgewerkt.

**Comment by joeribekker** [comment]
Behalve de preview functie kan ik niet veel met dit ticket dus ik assign je weer terug @FrankLieuwen
