### ISSUE TITLE
Preview uitlijning en kopjes

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#621]
### Product versie / Product version

actuele

### Omschrijf het probleem / Describe the bug

De preview voldoet niet aan de specificatie in #418

### Stappen om te reproduceren / Steps to reproduce

Open preview
- er worden kopjes van lege tekstblokken
- links en locaties in de rechterkolom zijn niet uitgelijnd met de generieke tekst en de specifieke tekst

![image](https://user-images.githubusercontent.com/96970/179245080-01194773-35c2-43de-919f-88b426639d6f.png)
![image](https://user-images.githubusercontent.com/96970/179245931-4329ab6e-5736-4517-bace-a8ef44f4adde.png)

### Verwacht gedrag / Expected behavior

Zie #418

**Comment by markbacker** [comment]
De label kopjes in de preview zijn niet te onderscheiden van de kopjes in de teksten. 
De label kopjes zijn in #418 gespecificeerd op H2. De tekstkopjes zijn H3 en H4.

graag fixen

**Comment by mrtn78** [comment]
@joeribekker kan jij deze als bug oppakken en verhelpen?
Mark heeft ingeschat dat dit niet voldoet aan de specificaties. 
Wieke verwacht dat dit voor veel verwarring en onduidelijkheid gaat leiden bij de gebruikers.

**Comment by joeribekker** [comment]
@mrtn78 Graag iets anders uit de sprint halen dan. Geef maar aan wat er uit mag.

**Comment by mrtn78** [comment]
@joeribekker pak deze maar op ipv slimmer filteren #607

**Comment by mrtn78** [comment]
opgelost in de laatste release en in productie
