### ISSUE TITLE
Monitoring en/of rapportages

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#624]
### Thema / Theme

CMS

### Omschrijving / Description

Monitoring van de voortgang van gemeenten

**User story**
Als SDG project wil ik weten in hoeverre gemeenten voldoen aan de SDG verordening, opdat ik kan bijsturen en verantwoorden

**Mogelijke oplossingen:**
- landkaart bij WaarStaatJeGemeente met status per gemeente (nog niks, account, eerste set producten klaar, NL klaar, NL en EN klaar)
- openzetten database voor Management Informatie tool
- wensen voor overzichten van implementatieadviseurs ...
- maatwerk rapportages in/naast de invoervoorziening
- ...

**Comment by mrtn78** [comment]
gesloten en content overgenomen in issue #663
