### ISSUE TITLE
Verwijderen/samenvoegen van een gemeente

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#625]
### Thema / Theme

Anders

### Omschrijving / Description

Hoe gaan we om het verwijderen en samenvoegen van gemeenten na herindeling.

Na een herindeling worden meerdere gemeenten heringedeeld tot 1 nieuwe gemeente. Wensen en vragen:
- Wat doen we met de organisatie en catalogus/producten van de te verwijderen gemeenten?
  - zie ook #408
  - verwijderen of in de API op einddatum kunnen filteren
  - wat zijn use cases voor productbeschrijvingen van niet meer bestaande gemeenten (waar ligt de archiveringsverantwoordelijkheid, portaal of CMS)
- Wat is de gewenste functionaliteit voor het aanmaken en vullen van de catalogus van een nieuwe gemeente
  - wanneer, kunnen gemeenten ruim voor de indeling definitief wordt (en voordat dit in de OWMS tabel staat) starten met de catalogus?
  - kunnen de teksten van de te verwijderen gemeenten gekopieerd worden naar de nieuwe catalogus
  - ...

### Aanvullende opmerkingen / Additional context

De softwarecatalogus heeft voor herindelingen functionaliteit voor het samenvoegen van gemeenten. De functioneel beheerder kan deze functie in overleg met de gemeenten gebruiken

**Comment by mrtn78** [comment]
Dit gaat iig spelen in de aanloop naar 2023. zie ook https://nl.wikipedia.org/wiki/Gemeentelijke_herindelingen_in_Nederland 

er komt dus iig 1 gemeente bij en er vallen er 3 af.

**Comment by joeribekker** [comment]
Ja, volgens mij kan het meeste al maar zal dit documenteren.

**Comment by mrtn78** [comment]
deels gedocumenteerd op https://github.com/maykinmedia/sdg-invoervoorziening/blob/master/docs/functioneel_beheer.md

**Comment by mrtn78** [comment]
De documentatie is bijgewerkt en beproefd op 1-1-2023
