### ISSUE TITLE
call to action aanvraag button / label bij decentrale procedurelink

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#662]
### Thema / Theme

API

### Omschrijving / Description

om op het Nationaal Portaal de link naar het aanvragen van een product te tonen als call to action button willen we naast de URL ook de tekst opgenomen hebben die op de button wordt getoond. Er moet dan dus een extra waarde worden ingevoerd door de gebruikers die ook wordt meegegeven in de api.

### Added value / Toegevoegde waarde

behalve een link op de pagin kan ook een button met tekst worden getoond waarmee gebruikers direct bij de aanvraag van het product bij de betreffende gemeente komen.

### Aanvullende opmerkingen / Additional context

Dit is aangedragen door Elie vanuit DOP

**Tasks**

* [ ] https://github.com/maykinmedia/sdg-invoervoorziening/issues/662#issuecomment-1185629716

**Comment by mrtn78** [comment]
Elie: ik denk dat het ook goed is om als richtlijn voor redacteuren mee te geven geen lange linkteksten te gebruiken. Dit is geen technisch eis maar meer een redactioneel advies. Je wilt bijv. niet een button hebben met de tekst 
> Klik hier om de standplaatsvergunning aan te vragen

maar liever

> Standplaatsvergunning aanvragen

**Comment by joeribekker** [comment]
Dit zorgt voor een breaking change!

Het attribuut "decentraleProcedureLink" wordt dan:
![image](https://user-images.githubusercontent.com/96970/179249923-e3719a86-6d8b-440f-860a-3debdc8fefe8.png)

ipv dit:
![image](https://user-images.githubusercontent.com/96970/179249978-4d8a5891-8feb-4ada-992f-5514890c04cf.png)

**Comment by joeribekker** [comment]
Hoge prio van gemaakt. Hoe eerder we hier doorheen bijten hoe beter
