### ISSUE TITLE
Generieke teksten API bevragen met query parameter upnUri

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#671]
### Thema / Theme

API

### Omschrijving / Description

De eerste versie van de generieke teksten API van DOP ondersteunde de query parameter upnLabel. Nu is deze uitgebreid met de parameter upnUri. 

Zie https://sdgapi.ondernemersplein.kvk.nl/docs/index.html

**Tasks**

* [x] Change the way we request data from the Generic texts endpoints periodically. We currently use the upnLabel but we should use the upnUri.

### Added value / Toegevoegde waarde

Identieke generieke teksten API van Rijksoverheid.nl en DOP, te bevragen met de in het SDG informatiemodel afgesproken key upnUri

**Comment by mrtn78** [comment]
dus de query parameter aanpassen naar het gebruik van de upnURI ipv de upnLabel
