### ISSUE TITLE
Product valt onder toelichting verbergen

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#673]
### Thema / Theme

CMS

### Omschrijving / Description

het veld product valt onder toelichting graag verbergen en alleen tonen wanneer een gebruiker een waarde heeft gekozen bij de dropdownlist van de optie "Product valt onder".
Zie ook:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1629141/177518018-60be53da-6bb5-4161-8d6e-89d615b36b57.png">

### Added value / Toegevoegde waarde

Door dit grote veld default te verbergen is er meer ruimte voor relevante content

### Aanvullende opmerkingen / Additional context

op verzoek van Rob opgevoerd

> Goedemorgen Martin, even een snel probleempje melden: Als je in de SDG een product opent zie je meteen het veld geopend "product valt onder toelichting" de hoort volgens mij pas te openen als je het veld "product valt onder" gebruikt! toch. Nu is het verwarrend en sluit het veld pas als je een product valt onder selecteert en deselecteert? Kan jij dit ASAP laten aanpaasen, Thanks

**Comment by joeribekker** [comment]
Opgelost in #683

**Comment by mrtn78** [comment]
issue is opgelost en in productie
