### ISSUE TITLE
API Keys niet verwijderen

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#709]
### Product versie / Product version

1.3.0

### Omschrijf het probleem / Describe the bug

Bij het overzetten van de data van productie naar acceptatie worden nu ook de API keys overschreven. daarmee worden impliciet de API keys voor acceptatie overschreven door de keys uit productie en daarmee zijn de acceptatie keys verwijdert.

Graag hier voor een uitzondering maken.

### Verwacht gedrag / Expected behavior

API keys blijven bestaan en worden niet gekopieerd bij het overzetten van data tussen omgevingen.

**Comment by sjoerdie** [comment]
Wijzigingen in backup / restore script doorgevoerd. Eerst volgende keer bij het overzetten wordt de api key behouden.
