### ISSUE TITLE
user secrets niet meenemen in het overzetten van prod naar acc

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#713]
### Thema / Theme

Admin

### Omschrijving / Description

user secrets, zoals wachtwoorden en MFA key's niet meenemen in de backup en restore (naar acceptatie). gebruikers moeten eigenlijk een nieuw wachtwoord aanvragen voor acceptatie.

### Added value / Toegevoegde waarde

uitsluiten dat gebruikers per ongeluk op acceptatie gaan werken.

**Comment by mrtn78** [comment]
zie ook #709

**Comment by sjoerdie** [comment]
Wijzigingen in backup / restore script doorgevoerd. Eerst volgende keer bij het overzetten worden user secrets cleared / reset.

**Comment by mrtn78** [comment]
> Wijzigingen in backup / restore script doorgevoerd. Eerst volgende keer bij het overzetten worden user secrets cleared / reset.

houdt dit in dat ook de user secrets van alle projectleden die op acc werken worden gereset? dan kan er niemand meer werken in acc want dan kunnen we de accounts niet meer herstellen.

**Comment by joeribekker** [comment]
@mrtn78 eh ja, dat is de wens toch:

> gebruikers moeten eigenlijk een nieuw wachtwoord aanvragen voor acceptatie.

**Comment by mrtn78** [comment]
De wens is dat Gebruikers niet moeten kunnen inloggen op de acc omgeving. Beheerders (met een staffstatus of zoiets) moeten ongemoeid worden gelaten. dit zijn immers de projectteam leden waarvoor de accounts bewust zijn aangemaakt. Deze worden nu ook overschreven en zelfs verwijdert.

**Comment by joeribekker** [comment]
Zoals besproken is dat lastig. Immers, gebruikers hebben een technisch ID en als dat technische ID meekomt vanuit productie wordt die specifieke gebruiker simpelweg overschreven.

Wat wel kan:

We zorgen dat bepaalde emailadressen hun wachtwoord mogen resetten op acceptatie. Dit moet dan elke gebeuren als data is overgezet. Het overzetten van data zal ook veel minder vaak nodig zijn als metabase is aangesloten.
