### ISSUE TITLE
Standaard engelse teksten laden bij lege velden

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#714]
### Thema / Theme

Admin

### Omschrijving / Description

Graag willen we mbv een script alle lege engelse velden vullen met de standaard tekst zodat gebruikers dit niet handmatig hoeven te doen. 

Dit is m.i. ontstaan doordat gebruikers de nederlandse tekst hebben bekeken/gewijzigd en opgeslagen en daarmee ook de engelse lege velden hebben opgeslagen. Daarna zijn de engelse standaard teksten ingeladen en deze worden niet getoond omdat eerder lege velden zijn opgeslag.

eventueel nog een fale safe inbouwen door de inlog en de publicatie waarde of andere logging te checken 

### Aanvullende opmerkingen / Additional context

Needs refinement.

**Tasks**

* [ ] Update empty English text-fields with the English reference texts IF that field is empty AND create a new (if there is none, otherwise update) concept with author=system

**Comment by joeribekker** [comment]
In overleg met VNG:

* Lege Engelse (tekst) velden bijwerken met de Engelse standaardteksten indien de tekst van de gemeente leeg is EN gepubliceerd is (of niet) voor X datum -> Maak hiervoor een nieuw concept aan (of als er al een concept is, werk dit concept bij - en zet in dit geval auteur op systeem).

**Comment by joeribekker** [comment]
@mrtn78 bepaald de datum X :)

**Comment by mrtn78** [comment]
@joeribekker de wijzigingen zijn rond 8 en 15 juli doorgevoerd dus we kunnen datum X met zekerheid stellen op 19-07-2022. dit is de dinsdag na het weekend waarvoor de laatste wijzigingen zijn doorgevoerd.

Kortom : X = 19-07-2022

**Comment by mrtn78** [comment]
Als onderdeel van de DOD dit script eerst uitvoeren in Acceptatie en controleren voor de uitrol in productie.
