### ISSUE TITLE
Testen generieke teksten API van DPC

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#768]
### Thema / Theme

API

### Omschrijving / Description

De SDG API Generieke Teksten van DPC staat op https://a-api.nederlandwereldwijd.nl/sdg/gt/v1/producten en is gereed voor testen.

We horen graag hoe de API aansluit bij de SDG invoervoorziening van de VNG, inclusief natuurlijk verbeterpunten en inconsistenties.

**Comment by joeribekker** [comment]
Er is geen schema beschikbaar. Daar gaan we wel van uit. Werkt dus niet.

**Comment by markbacker** [comment]
Hierbij de documentatie en het schema. 
- [DPC-20-9-2022-v1.0-Documentatie+Generieke+Teksten+SDG+API.doc.pdf](https://github.com/maykinmedia/sdg-invoervoorziening/files/9799161/DPC-20-9-2022-v1.0-Documentatie%2BGenerieke%2BTeksten%2BSDG%2BAPI.doc.pdf)
- [DPC-20-9-2022-v1.0-API-GT-openapi.json.zip](https://github.com/maykinmedia/sdg-invoervoorziening/files/9799221/DPC-20-9-2022-v1.0-API-GT-openapi.json.zip)

**Comment by gberkouwer** [comment]
Laat even weten als iets niet duidelijk is.

**Comment by mrtn78** [comment]
Dit werkt inmiddels
