### ISSUE TITLE
Remove signup process

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#784]
**Tasks**

* [x] Only sent password reset mails if the emailaddress exists (so no signup feature)
* [x] Remove page to signup for an account (that is linked in the above email when the emailaddress does not exist)

**Comment by dariomory** [comment]
@joeribekker  I suggest sending the email anyway. Sending the email is a security setting by django-allauth and it prevents enumeration. 

Two options:
1. Modify the email template.
2. Show the email is sent without sending anything.
