### ISSUE TITLE
'Titel gemeenteproduct' standaard ingevuld

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#786]
### Thema / Theme

CMS

### Omschrijving / Description

We willen dat de 'Titel gemeenteproduct' standaard is ingevuld. Deze moet gelijk zijn aan titel van de generieke tekst. Verandert de titel van de generieke tekst? Dan wijzigt dus ook automatisch de titel gemeenteproduct. 
Daarnaast willen we graag een zin onder dit veld plaatsen met een soort instructie (vergelijkbaar met het telefoonnummer en mailadres bij de algemene gegevens). Het zou helemaal mooi zijn als ik deze tekst zelf kan aanpassen. Dan kan ik dit gemakkelijk wijzigen naar aanleiding van ontwikkelingen binnen de designs van de Nationale Portalen. 
(Groetjes Wieke )

### Added value / Toegevoegde waarde

redacteuren vinden het tegennatuurlijk om het eerste invulveld met de specifieke titel leeg te laten. vandaar dat ze deze vaak invullen en hierbij ontstaat het risico dat er kleine verschillen in schrijfwijze of interpunctie ontstaan.

### Aanvullende opmerkingen / Additional context

Het lijkt mij praktisch als we de specifieke titel niet iedere keer overschrijven want dan moeten we die ook impliciet opslaan als iemand de pagina verlaat. Wellicht dus handiger om in het veld specifieke titel de generieke titel te tonen indien er geen of nog geen specifieke titel is.

**Comment by joeribekker** [comment]
Okay, bij nieuwe producten vullen we titel met de generieke titel als standaard waarde.

Dan nog enkele opties (graag kiezen):

1. Moeten we alle titel velden nu eenmalig vullen (overschrijven) met de generieke titel?
2. Moeten we het titel veld in het CMS weghalen of alleen-lezen maken?

**Comment by mrtn78** [comment]
Het gaat er niet om dat we het veld vullen of de waarden overschrijven.
We willen het veld ook in het CMS niet weghalen of alleen lezen maken.

Indien het veld specifieke titel leeg is dan de generieke titel tonen in het veld specifieke titel.
bij het opslaan van de specifieke tekst het velde specifieke titel leeg laten indien de specifieke titel gelijk is aan de generieke titel.
