### ISSUE TITLE
Relative url en absolute url verschillen

### ISSUE THREAD

**Issue by scirikka** [maykinmedia/sdg-invoervoorziening#790]
### Product versie / Product version

1.4.0

### Omschrijf het probleem / Describe the bug

De url onder verantwoordelijke organisatie is relative. De overige urls zijn echter absoluut. 

### Stappen om te reproduceren / Steps to reproduce

Go to https://pdc.data.vng.nl/sdg/api/v1/producten?doelgroep=eu-burger&upnUri=http://standaarden.overheid.nl/owms/terms/geboorteaangifte&organisatieOwmsIdentifier=http://standaarden.overheid.nl/owms/terms/Goes_(gemeente)

### Verwacht gedrag / Expected behavior

Absoluut path voor urls.

**Comment by joeribekker** [comment]
Goed opgemerkt, is inderdaad een bug.

Plaatje ter verduidelijking:

![image](https://user-images.githubusercontent.com/96970/195990233-2f594cbd-97b4-44f8-a0b5-7afc504229a7.png)
