### ISSUE TITLE
Make loading generic products more robust

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#791]
Currently, we override the operationId "productenList" with a specific path. However, this doesn't work with the other API endpoint that we need to consult. Their API schema is absent (so we cannot load it) and it uses different paths.

Their API is located on: `https://a-api.nederlandwereldwijd.nl/sdg/gt/v1/producten` (only accessible from whitelisted IPs)

**Comment by dariomory** [comment]
@joeribekker Let's proceed after we can get the network whitelisted for development purposes.

**Comment by alextreme** [comment]
@dariomory this API is accessible via the office and via Rachel, no reason to be blocked

**Comment by joeribekker** [comment]
Indeed, office is whitelisted
