### ISSUE TITLE
Check if products with status "verwijderd" are also not shown in the API

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/sdg-invoervoorziening#809]
* [x] Check if products with product status "verwijderd" are also not present in the API (they are hidden in the CMS product list view)
* [x] Add a test for this

**Comment by dariomory** [comment]
@joeribekker Let's conclude https://github.com/maykinmedia/sdg-invoervoorziening/pull/774 before proceeding with this.

**Comment by joeribekker** [comment]
Good point. It wasn't needed anymore from a management perspective, but now it became technical. #774 is merged.
