### ISSUE TITLE
Foute suffix eu-burger/eu-ondernemer / fouten in productlijst

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#815]
### Product versie / Product version

1.5

### Omschrijf het probleem / Describe the bug

Zie onderstaande screenshot voor een aantal producten waarbij onterecht een suffix "eu-burger" of " - " wordt toegevoegd. Eerste is omgevingsvergunning kap -
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1629141/203061080-0d0ae11c-3aae-4687-9bc7-7bf44ab26245.png">

### Stappen om te reproduceren / Steps to reproduce

Eerste screenshot
- Ga naar https://pdc-acc.vng.nl/sdg/organizations/147/productenlijst/2/products/33062/edit/
- Open dropdown subproduct

### Verwacht gedrag / Expected behavior

het verwachte gedrag is dat je in de dropdown lijst van subproducten dezelfde lijst ziet als welke ook op de productenpagina wordt getoond

### Tasks

* [x] The list of products shown in the "product valt onder" dropdown, should be the same list as products shown on the product list page. The query now differs and shows expired, etc. products.
* [x] Remove the postfix dash ("-") if there is no "doelgroep".

**Comment by joeribekker** [comment]
Ik zie hier 3 gerapporteerde issues die allen op de testomgeving zijn. Ik raad aan ze te hertesten op acceptatie, en 3 losse issues aan te maken.

**Comment by mrtn78** [comment]
hi Joeri, 

Ik heb de omschrijving bijgewerkt en het is 1 bug waarbij de dropdownlijst van producten een andere querie heeft dan de lijst van producten op de productenpagina. je ziet bijvoorbeeld producten terug in de dropdown die geen doelgroep hebben en producten die de status verwijdert hebben. Daarom graag als bugfix oppakken en herstellen.
