### ISSUE TITLE
[US-44] Als Beheerder Invoervoorziening wil ik de generieke teksten bij de NP kunnen raadplegen, opdat ik altijd de actuele versie gebruik 

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#82]
De generieke teksten zijn gedefinieerd in het [Informatie model 1.3.xlsx](https://github.com/maykinmedia/sdg-invoervoorziening/files/7176323/Informatie.model.1.3.xlsx)
- voor SDG producten worden de attributen onder Product (generiek) beheerd door de Nationale Portalen en zullen ontsloten worden met een API (planning Q2 2022)
- de invoervoorziening raadpleegt de NP API product generiek

**Comment by FrankLieuwen** [comment]
voor opnemen in sprint overleggen met PO

**Comment by markbacker** [comment]
Dit is met #444 opgelost.
