### ISSUE TITLE
"Zie ook" geeft problemen met dubbel labelvermelding binnen gemeenten producten

### ISSUE THREAD

**Issue by RobbieZ69** [maykinmedia/sdg-invoervoorziening#835]
### Product versie / Product version

huidige productie

### Omschrijf het probleem / Describe the bug

Melding van gemeente Zoetermeer, gebruiker Berg - Mooyman.

Voorbeeld: als ik 2x het label ‘bijstand’ intyp met een url, dan krijg ik bij het 2e product waar ik dat wil gebruiken deze melding. zie afbeelding

Op het moment dat ik dan het label aanpas naar ‘bijstand aanvragen’ met dezelfde url, dan pakt het systeem het wel en wordt alles opgeslagen.

 
![thumbnail_image001](https://user-images.githubusercontent.com/58431027/202193042-a9a12363-ba67-4be3-b258-af7475f5c48d.png)

**Comment by joeribekker** [comment]
Ik vermoed dat dit opgelost is in 1.5.0 en kwam door de "komma" in het label.

Kan jij dat testen @RobbieZ69 ?

**Comment by RobbieZ69** [comment]
Ik ga het navragen, kan het zelf niet testen. Je hoort het nog.

Gr. Rob

met vriendelijke groet,

Rob van Linden
RobbieZ-Media
Fotografie/Grafische vormgeving en ICT-Diensten
Tollensstraat 27
2712 EG Zoetermeer
0624133029

________________________________

**Comment by mrtn78** [comment]
Ik heb het zelf even getesten het werkt nu naar behoren. Alleen nog even toevoegen aan de release notes.

**Comment by joeribekker** [comment]
Dit is getackled in 1.5.0 via #807
