### ISSUE TITLE
header productenlijst verbeteren

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#837]
### Product versie / Product version

1.5.0

### Omschrijf het probleem / Describe the bug

Als opvolging op issue #751 is de opmaak is nu erg vreemd omdat bij publicatiedatum het grijze selectievlak ontbreekt:
![image](https://user-images.githubusercontent.com/1629141/203102871-6603874f-cf0e-43c6-8a0f-f9b3be8ac2d5.png)

### Stappen om te reproduceren / Steps to reproduce

Goto https://pdc-acc.vng.nl/sdg/organizations/147/productenlijst/

### Verwacht gedrag / Expected behavior

eenduidige opmaak van de header van de kolommen

### Tasks

* [x] Move "Heeft kosten" one column to the left, so that "publicatiedatum" is the far right column.

**Comment by joeribekker** [comment]
Laten we de kolom gewoon eentje opschuiven, toch? Dan is het weer als vanouds. Dit is geen bug overigens.
