### ISSUE TITLE
Valideren tekstblokken met restanten standaardtekst

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#842]
### Thema / Theme

CMS

### Omschrijving / Description

Nu
- tekstblokken worden niet gevalideerd. 

Straks
- tekstblokken worden gecontroleerd of er nog een 'marker' of 'placeholder' uit de standaardtekst in staat. 
- Zoeken op:
  - **markers**
    - `\[`
	  - `\[opti`
		  - \[optie n\]
		  - \[optioneel\]
	  - `\[Opti`
		  - \[Optie n\]
		  - \[Optioneel voor optie 1\]
	  - `\[extra optie\]`
  - **placeholders**
    - `\[`
	  - `\[contact`
		  - \[contactgegevens\]
		  - \[contactgegevens gemeente\]
      - `\[link`
		  - \[link naar gemeente pagina of contactgegevens voor meer info\].
		  - \[linkje naar download formulieren\]
		  - \[link naar download formulieren\]
	  - `\[of andere datum\]`
	  - `\[or another date\]`
	- `XX|xx`
		- \[xx\] 
		- € XX
		- € xx
		- EUR XX
	    -  XX weeks
    - `XXX|xxx`
	  -  € XXX
	  -  xxx weeks
    -  `XXXX`
       - Account number: XXXX 
       - Rekeningnummer: XXXX  
- teksten met een tekstblok met een marker of placeholder kunnen
  - opgeslagen worden als concept (er wordt een waarschuwing getoond dat er nog een marker of placeholder uit de standaardtekst in de tekst staat)
  - **niet** gepubliceerd worden (er wordt een foutmelding getoond dat er nog een marker of placeholder uit de standaardtekst in de tekst staat)

### Added value / Toegevoegde waarde

Gemeenten kunnen geen teksten met opzichtige fouten publiceren

**Comment by joeribekker** [comment]
Ik kan 3 dingen doen:

1. Deze lijst overnemen tot een bepaald niveau (geef even aan welk niveau)
2. Lijst configureerbaar maken in admin
3. Gewoon "XX" en "[" verbieden? :)

@markbacker kan jij aangeven wat je wilt?

Optie 3 is veruit het snelst. 2 duurt het langst.

**Comment by joeribekker** [comment]
In overleg ticket #856 gemaakt
