### ISSUE TITLE
Valideren `valt_onder_toelichting`

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#843]
### Thema / Theme

CMS

### Omschrijving / Description

nu
- `valt_onder_toelichting` wordt altijd opgeslagen, ook als de gemeente niets aan de vooringevulde tekst heeft veranderd

wijziging:
- bij het opslaan van de specifieke tekst het veld `valt_onder_toelichting` leeg laten indien de `valt_onder_toelichting` gelijk is aan de vooringevulde tekst.

### Added value / Toegevoegde waarde

Verhogen van de kwaliteit van de ingevoerde toelichtingen

Gemeenten die de standaard toelichting gebruiken (de meeste blijkt uit de monitor) gebruiken zo altijd een actuele toelichting. De toelichting kan wijzigen door een gewijzigde generieke titel (als productnaam) of een andere vooringevulde tekst. 

### Tasks

* [ ] When product is saved in the CMS, check if the `product_valt_onder_toelichting` is exactly the same as the "default" text. If so, leave the field empty. Remember that JS modifies the text with the organization name/selected product name.

**Comment by joeribekker** [comment]
Zie #841 commentaar. Ik gebruik deze user story enkel voor het veldje, de rest is gelijk volgens mij.
