### ISSUE TITLE
Productlijst van de standaardteksten organisatie is leeg.

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#855]
### Product versie / Product version

1.5.0

### Omschrijf het probleem / Describe the bug

De VNG catalogus met referentieteksten is leeg.

Maar de productlijst van Harderwijk niet, zie *snip* prod /organizations/147/productenlijst/
En op acceptatie is de VNG lijst wel gevuld *snip* acc /organizations/421/productenlijst/

Wat gaat er mis?

### Stappen om te reproduceren / Steps to reproduce

Ga naar *snip* prod /organizations/421/productenlijst/

### Screen resolution

bigger

### Browser

Desktop

### Browser

Firefox

**Comment by joeribekker** [comment]
Opgelost.
