### ISSUE TITLE
duplicates in "/producten" and /organisaties

### ISSUE THREAD

**Issue by scirikka** [maykinmedia/sdg-invoervoorziening#859]
### Product versie / Product version

1.5.1

### Omschrijf het probleem / Describe the bug

The "/producten" endpoint has several duplicates in place.

As an example:

https://pdc.data.vng.nl/sdg/api/v1/producten?page=1
https://pdc.data.vng.nl/sdg/api/v1/producten?page=2

Both contain "aangifte vertrek buitenland" for the municipality "Katwijk" with the same url and identical fields. 

{
      "url": "https://pdc.data.vng.nl/sdg/api/v1/producten/3dc9f8cb-0949-4d47-988b-80e01d235f71",
      "uuid": "3dc9f8cb-0949-4d47-988b-80e01d235f71",
      "upnLabel": "aangifte vertrek buitenland",
      "upnUri": "http://standaarden.overheid.nl/owms/terms/AangifteVertrekBuitenland",
      "versie": 1,
      "publicatieDatum": null,
      "productAanwezig": true,
      "productValtOnder": null,
      "verantwoordelijkeOrganisatie": {
        "url": "https://pdc.data.vng.nl/sdg/api/v1/organisaties/818f73e1-2f93-4a19-a346-e8c7dad97eb6",
        "owmsIdentifier": "http://standaarden.overheid.nl/owms/terms/Katwijk_(gemeente)",
        "owmsPrefLabel": "Katwijk",
        "owmsEndDate": null
      },
      "bevoegdeOrganisatie": {
        "naam": "Katwijk",
        "owmsIdentifier": "http://standaarden.overheid.nl/owms/terms/Katwijk_(gemeente)",
        "owmsPrefLabel": "Katwijk",
        "owmsEndDate": null
      },
      "catalogus": "https://pdc.data.vng.nl/sdg/api/v1/catalogi/03ca304c-7e9c-49c8-93a2-bc0361f7e4b9",
      "locaties": [],
      "doelgroep": "eu-burger",
      "vertalingen": [
        {
          "taal": "nl",
          "titel": "",
          "tekst": "Let op. U kunt uw verhuizing naar het buitenland alleen doorgegeven als u in Nederland woont en bent ingeschreven bij een gemeente.",
          "links": [],
          "procedureBeschrijving": "*   Verhuist u alleen naar het buitenland? Dan kunt u uw vertrek online doorgeven. \r\n*   Verhuist niet uw hele gezin naar het buitenland? Dan moet u uw vertrek schriftelijk of aan de balie van de gemeente doorgeven.\r\n\r\n### **Online**\r\n\r\nU kunt uw vertrek online doorgeven op de dag van uw verhuizing. U heeft hiervoor DigiD nodig.\r\n\r\n\\[formulier vertrek doorgeven met DigiD\\]\r\n\r\n### **Schriftelijk**\r\n\r\nU kunt uw verhuizing alleen per post doorgeven als alle personen van uw gezin meeverhuizen.\r\n\r\n\\[optie 1\\]\r\n\r\nVul het \\[formulier vertrek buitenland\\] helemaal in. Stuur het formulier samen met een kopie van een geldig paspoort, Nederlandse identiteitskaart of verblijfsdocument van u en uw gezin naar \\[adres xxx\\].\r\n\r\n\\[optie 2\\]\r\n\r\nMaak een ondertekende brief met uw oude en (als dat al bekend is) nieuwe adres. \r\n\r\nIn de brief moet staan:\r\n\r\n*   in welk land u gaat wonen;\r\n*   de datum van uw vertrek;\r\n*   een duidelijke handtekening (geen paraaf).\r\n\r\nStuur deze brief samen met een kopie van uw identiteitsbewijs naar \\[adres xxx\\]. Of mail alle documenten naar \\[mailadres\\].\r\n\r\n### **Aan de balie**\r\n\r\nWilt u het vertrek van u en uw gezin doorgeven aan de balie? Maak eerst een afspraak via \\[pagina gemeente\\]. Neem uw geldige legitimatiebewijs mee naar uw afspraak.\r\n\r\nBij de afspraak moet u uw nieuwe adres doorgeven, als dat al bekend is. U moet altijd doorgeven in welk land u gaat wonen.\r\n\r\nU kunt tegelijk met het vertrek van uzelf het vertrek doorgeven van deze personen:\r\n\r\n*   uw echtgenoot of echtgenote;\r\n*   uw geregistreerde partner;\r\n*   uw kinderen;\r\n*    uw ouders.\r\n\r\nDeze personen moeten wel bij u op hetzelfde adres staan ingeschreven.\r\n\r\nHeeft u een samenlevingscontract? Dan geven u en uw partner apart het vertrek naar het buitenland door.",
          "bewijs": "",
          "vereisten": "",
          "bezwaarEnBeroep": "",
          "kostenEnBetaalmethoden": "Het doorgeven van een verhuizing is gratis.",
          "uitersteTermijn": "*   Doorgeven via e-mail of post: duurt 5 werkdagen.\r\n*    Doorgeven aan de balie: verwerkt de gemeente direct.",
          "wtdBijGeenReactie": "",
          "procedureLink": {
            "label": "",
            "url": ""
          },
          "productAanwezigToelichting": "",
          "productValtOnderToelichting": "",
          "datumWijziging": "2022-06-09T10:06:31.947176"
        },
        {
          "taal": "en",
          "titel": "",
          "tekst": "",
          "links": [],
          "procedureBeschrijving": "",
          "bewijs": "",
          "vereisten": "",
          "bezwaarEnBeroep": "",
          "kostenEnBetaalmethoden": "",
          "uitersteTermijn": "",
          "wtdBijGeenReactie": "",
          "procedureLink": {
            "label": "",
            "url": ""
          },
          "productAanwezigToelichting": "",
          "productValtOnderToelichting": "",
          "datumWijziging": "2022-06-09T10:06:31.949388"
        }
      ],
      "beschikbareTalen": [
        "nl",
        "en"
      ]
    }

### Stappen om te reproduceren / Steps to reproduce

- Go to https://pdc.data.vng.nl/sdg/api/v1/producten?page=1 and https://pdc.data.vng.nl/sdg/api/v1/producten?page=2
- Search for "Katwijk"

### Verwacht gedrag / Expected behavior

"/producten" endpoint has no duplicates, or a newer text for the same municipality and same upn has a different version number

**Comment by scirikka** [comment]
This seems to also be the issue in "/organisaties":

Page 1 and Page 2 have a lot of duplicates:

https://pdc.data.vng.nl/sdg/api/v1/organisaties?page=1
https://pdc.data.vng.nl/sdg/api/v1/organisaties?page=2

**Comment by joeribekker** [comment]
Thanks for the observation. We will look into it!
