### ISSUE TITLE
Als redacteur wil ik graag een spellingscontrole op mijn ingevoerde teksten

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#864]
### Thema / Theme

CMS

### Omschrijving / Description

Van een ingevoerde tekst wordt de spelling gecontroleerd (EN en NL). Spelfouten worden gemarkeerd met een kringeltje. Hoveren/klikken op het kringeltje toont suggesties voor de correctie.

### Added value / Toegevoegde waarde

Verbeteren kwaliteit van de teksten

**Comment by joeribekker** [comment]
Ik zou dit niet maken, browsers hebben spellingcontroles en alle Word documenten waar de teksten uit komt ook. Dit is anders geen kleine feature.

**Comment by markbacker** [comment]
Nou ja zeg, inderdaad. Ik kan Firefox zo instellen dat zowel de spelling in NL als EN gecontroleerd wordt. Een snelle search laat zien dat chrome en edge dit ook kunnen. Je moet het alleen even weten ... 

We kunnen dit dus met een instructie oplossen.

**Comment by joeribekker** [comment]
Graag bespaard ;-)

**Comment by mrtn78** [comment]
@markbacker wil jij dit issue bijwerken met de nieuwe inzichten?
ik zet m weer terug op jou naam en je mag m dan ook sluiten uiteraard.

**Comment by markbacker** [comment]
Oplossen met een korte instructie voor redacteuren (voor bv. de browsers edge, chrome en firefox)
