### ISSUE TITLE
"publicatieDatum__gte" returns products with a "publicatieDatum" value of null

### ISSUE THREAD

**Issue by scirikka** [maykinmedia/sdg-invoervoorziening#877]
### Product versie / Product version

1.5.1

### Omschrijf het probleem / Describe the bug

The "publicatieDatum__gte" filter occasionaly returns products of which the "publicatieDatum" is null.

An example: https://pdc.data.vng.nl/sdg/api/v1/producten?page=1&publicatieDatum__gte=2000-01-01

`{
            "url": "https://pdc.data.vng.nl/sdg/api/v1/producten/35556045-6c6e-4f89-8a11-761b42294e0f",
            "uuid": "35556045-6c6e-4f89-8a11-761b42294e0f",
            "upnLabel": "aangifte vertrek buitenland",
            "upnUri": "http://standaarden.overheid.nl/owms/terms/AangifteVertrekBuitenland",
            "versie": 6,
            "publicatieDatum": null,
...
}`

The ones which do return null seem to all have a "versie" > 1

### Stappen om te reproduceren / Steps to reproduce

go to https://pdc.data.vng.nl/sdg/api/v1/producten?page=1&publicatieDatum__gte=2000-01-01
search for "publicatieDatum": null

### Verwacht gedrag / Expected behavior

if "publicatieDatum__gte" is filled in, null should be filtered out.

### Screen resolution

None

### Browser

None

### OS

None

**Comment by joeribekker** [comment]
Should be fixed with the performance update in 1.6.0
