### ISSUE TITLE
Intern opmerkingen veld wordt gewist bij de keuze: Heeft jou gemeente dit product "Nee" ?

### ISSUE THREAD

**Issue by RobbieZ69** [maykinmedia/sdg-invoervoorziening#881]
### Product versie / Product version

laatste

### Omschrijf het probleem / Describe the bug

Als de gebruiker het veld vult, product bewerkt, maar toch, tijdelijk, kiest voor het product op Nee te zetten i.v.m. publicatie/nog niet klaar. verdwijnt de tekst uit het tekst veld? Dit draag met hoge spoed oplossen, is nl een workaround die wij voorstellen als een gemeente een product nog niet helemaal klaar heeft wat teksten betref voor a.s. maandag 12 dec.

### Screen resolution

unknown

### Browser

Desktop

### OS

Windows

### Browser

Anders / Other

**Comment by joeribekker** [comment]
Interne opmerkingen worden enkel opgeslagen in de historie. Ik kan niet vinden waar dit anders is gespecificeerd?
