### ISSUE TITLE
Verhuis optie gemeente binnen PDC geeft foutmelding!

### ISSUE THREAD

**Issue by RobbieZ69** [maykinmedia/sdg-invoervoorziening#882]
### Product versie / Product version

huidige

### Omschrijf het probleem / Describe the bug

Wij hebben voor komend jaar een wijziging in gemeenten wat reeds bekend is:  Brielle, Westvoorne, Hellevoetsluis  WORDT>>Voorne aan Zee
Tijdens het proberen in acceptatie omgeving, verhuizen van gegevens zoals beschreven kregen wij een foutmelding dat dit mogelijk was?
We volgen de stappen die voorgeschreven zijn, maar dan nog? Kan jij aangeven waarom dit gebeurt, graag met enige spoed 😉

### Screen resolution

unknown

### Browser

Anders / Other

### OS

Anders / Other

**Comment by joeribekker** [comment]
Verhuist naar beheer issue.
