### ISSUE TITLE
Tekst met een link kan niet meer gepubliceerd worden (blokhaken in link wordt gezien als placeholder)

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#886]
### Product versie / Product version

1.6

### Omschrijf het probleem / Describe the bug

Fout in oplossing voor #842

Publiceren van een tekst met daarin een geldige link \[test\](test.nll) geeft foutmelding "De tekst mag geen placeholders bevatten." 

Een link is geen placeholder

De foutmelding maakt niet duidelijk wat een placeholder is. Suggestie voor nieuwe foutmelding:
> Verwijder uit de tekst de placeholders van de standaardtekst (placeholders zijn [opties] en XX)

### Stappen om te reproduceren / Steps to reproduce

1 Ga naar https://sdg-invoervoorziening.maykin.nl/sdg/organizations/2/productenlijst/2/products/332/edit/

2 publiceer deze tekst.
3 verwijder de link
4 publiceer de tekst

### Screen resolution

None

### Browser

None

### OS

None

**Comment by joeribekker** [comment]
1.6 is nog niet uit :P
