### ISSUE TITLE
Kan product niet meer publiceren. Meldingen bovenin kloppen niet

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#893]
### Product versie / Product version

1.6

### Omschrijf het probleem / Describe the bug

Bij het publiceren van een product krijg ik de foutmelding
> Wijzigingen konden niet worden opgeslagen. Corrigeer de hieronder gemarkeerde fouten.

Maar er zijn geen fouten gemarkeerd.

Als ik hetzelfde product opsla als concept, zie ik de melding:
> De huidige gegevens bevatten placeholder tekst.

Maar deze worden niet gemarkeerd.
Ik kan geen placeholders in de tekst meer vinden. Waar o waar?

Na het opslaan als concept staat bovenin ook de melding:
> U bewerkt een concept product tekst.

Dat klopt

Na het publiceren, staat er de melding
> U bewerkt een reeds gepubliceerde producttekst. Als u deze opslaat wordt een nieuwe versie aangemaakt.

en dat klopt niet. Want het publiceren is niet gelukt.

### Stappen om te reproduceren / Steps to reproduce

Ga naar https://pdc-acc.vng.nl/sdg/organizations/147/productenlijst/2/products/52580/edit/

en klik om en om op [opslaan als concept] en [publiceren]

### Verwacht gedrag / Expected behavior

Ook na opslaan als concept met de melding 
> De huidige gegevens bevatten placeholder tekst.
verwacht ik dat de fouten gemarkeerd worden.

Na het publiceren moeten de fouten ook gemarkeerd worden.

Nu zijn er geen placeholders (of ik lees erover), dan moet je kunnen publiceren

### Screen resolution

None

### Browser

None

### OS

None

**Comment by joeribekker** [comment]
De foutmelding is niet helemaal duidelijk omdat je hoogstwaarschijnlijk in de Engelse variant een placeholder hebt, maar je standaard op de Nederlandse variant staat. De foutmelding klopt dus, en je kan ook opslaan, mits je alle placeholders bij alle vertalingen weghaalt.

@mrtn78 heeft dit gecheckt, en de foutmelding is hierop aangepast.
