### ISSUE TITLE
Score security headers verbeteren

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#916]
### Thema / Theme

CMS

### Omschrijving / Description

Als Beheerder wil ik minimaal een A score op de security headers. Zodat ik aan de gemeenten kan laten zien dat we er alles aan doen om de beveiliging op orde te houden. Zie ook https://securityheaders.com/?q=https%3A%2F%2Fpdc.vng.nl%2F&hide=on&followRedirects=on

**Comment by joeribekker** [comment]
CSP-headers is niet zomaar even een headertje toevoegen.

**Comment by mrtn78** [comment]
Dit issue is verouderd en niet direct noodzakelijk.
