### ISSUE TITLE
Gemeente mag product niet publiceren met aangeboden=onbekend

### ISSUE THREAD

**Issue by markbacker** [maykinmedia/sdg-invoervoorziening#931]
### Thema / Theme

CMS

### Omschrijving / Description

Bij het publiceren van een product moet worden gecontroleerd of `productAanwezig` de waarde Ja of Nee heeft.
Bij het aanmaken van een producttekst voor een gemeente wordt `productAanwezig` default op Ja gezet (nu is de default Onbekend)

Als een gemeente een product wil publiceren met `productAanwezig` = Onbekend wordt een foutmelding getoond:
- Je hebt nog niet aangegeven of jouw gemeente dit product aanbiedt. Geef dit aan met Ja of Nee. Let op! Je kan deze pagina alleen publiceren als je een keuze hebt gemaakt. 
> @Wieke levert nog de definitieve tekst aan

### Added value / Toegevoegde waarde

Het is voor de burger en ondernemer (en dus ook de portalen) altijd expliciet welke producten een gemeente wel en niet aanbiedt 

### Aanvullende opmerkingen / Additional context

Graag overleg over hoe dit doorwerkt op het opslaan en publiceren van de standaardteksten in de VNG referentiecatalogus. Deze staan nu allemaal op Onbekend

**Comment by joeribekker** [comment]
Refeinment: Wieke levert nog de definiteve tekst aan van de foutmelding.
