### ISSUE TITLE
Placeholder blokkeert "product niet aangeboden en Valt onder"

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#933]
### Thema / Theme

CMS

### Omschrijving / Description

De nieuwe functie placeholder blokkeert het publiceren als er [] of XX zijn voor publiceren. Alleen dit wordt ook geblokkeerd als men "Heeft jou gemeente dit product" en "Dit product valt onder" gebruikt en respectievelijk op "Nee' zet of verwijst naar een ander product. Dit is niet gewenst. 
Is een mogelijke oplossing om bij de keuze "nee" bij "heeft jou gemeente dit product" om de tekst velden automatisch leeg te maken bij "nee"?* Dit horen we graag.

*Als deze optie, tekst automatisch verwijderen, leidt tot extra kosten horen we dit graag.

### Aanvullende opmerkingen / Additional context

Dit issue lost taiga [issue 52](https://taiga.maykinmedia.nl/project/vng-sdg-invoervoorziening/issue/52) op en verbetert de gebruikersinteractie

**Comment by joeribekker** [comment]
Refinement: Validatie uitschakelen en niet de tekst leegmaken.

**Comment by joeribekker** [comment]
Met Rob besproken: Als je "productValtOnder" of "productNietAangeboden" aanzet, dan moet je de rest allemaal niet meer valideren (zoals op placeholders) want die zijn niet relevant immers.
