### ISSUE TITLE
teksten aanpassen door beheer

### ISSUE THREAD

**Issue by mrtn78** [maykinmedia/sdg-invoervoorziening#934]
### Thema / Theme

CMS

### Omschrijving / Description

Als beheerder willen we een script:
Dit komt voort uit [Taiga issue 53](https://taiga.maykinmedia.nl/project/vng-sdg-invoervoorziening/issue/53)

> Vervang de gegenereerde zinnen die eindige op "omdat …" met "." inclusief engelstalige varianten.
> 
> Bijvoorbeeld: 
> "De gemeente {gemeente} levert het product {product} niet omdat…" -> "De gemeente {gemeente} levert het product {product} niet."

### Added value / Toegevoegde waarde

De toegevoegde waarde is dat we meer consistente en eenduidige teksten hebben die goed overkomen op de Nationale portalen zonder dat we hiervoor heel veer gemeenten hoeven aan te sporen dit zelf te doen.

### Aanvullende opmerkingen / Additional context

eenmalig een script maken en uitvoeren om deze content aan te passen

**Tasks**

* [ ] Create datamigration to replace " omdat..." (and " omdat ...") with "." in `*_toelichting`-fields (2 of them)

**Comment by joeribekker** [comment]
Het is mij onduidelijk wat jullie precies willen. Wat voor teksten willen jullie vervangen? Statische teksten of ingevoerde teksten van gemeenten? Of standaard teksten?

**Comment by mrtn78** [comment]
> Het is mij onduidelijk wat jullie precies willen. Wat voor teksten willen jullie vervangen? Statische teksten of ingevoerde teksten van gemeenten? Of standaard teksten?

Met name de teksten van gemeenten.

**Comment by RobbieZ69** [comment]
Hoi Joeri, Zoals afgesproken zou ik e.a. nog even aanvullen: Eerste stap is idd gezet, dat de tekst van een product wat niet wordt aangeboden eindigt met een punt i.p.v. omdat....
Maar wat wij dan graag zien gebeuren is dat in de gehele invoervoorziening is dat de tekst zoals deze nu in de nieuwe situatie wordt neergezet overal komt te staan, alles vervangen en het gehele veld "Product aanwezig toelichting" verwijderen, zodat er ook geen twijfel over kan ontstaan. Kan jij aangeven wat dit gaat kosten en of het wijs is om dit voor alle portalen te regelen, zodat we dit gezamenlijk betalen? Hoor het graag.

p.s. als iets onduidelijk is hoor ik het graag.

**Comment by joeribekker** [comment]
Ik laat dit issue gesloten en heb #962 aangemaakt hiervoor.

**Comment by RobbieZ69** [comment]
Top!

met vriendelijke groet,

Rob van Linden
RobbieZ-Media
Fotografie/Grafische vormgeving en ICT-Diensten
Tollensstraat 27
2712 EG Zoetermeer
+31 853016096
________________________________
